#!/bin/sh

# These variables are always available to this script:
# The path to the file containing the commit message.
COMMIT_MSG_FILE=$1
# A description of the source of the commit.
COMMIT_SOURCE=$2
# The commit SHA.
SHA1=$3

# If our branch is formatted to represent a JIRA ticket, prepend the JIRA ticket
# ID to our commit message.
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
TICKET_ID="$(echo "${BRANCH}" |
  grep -E -o --color=never '^[A-Z]+-[0-9]+' 2>/dev/null)"

if [ -n "${TICKET_ID}" ]; then
  echo "$(
    printf "%s: " "${TICKET_ID}"
    cat "${COMMIT_MSG_FILE}"
  )" >"${COMMIT_MSG_FILE}"
fi
