#!/usr/bin/env bash

# Trap errors and print error message
set -uo pipefail
trap 's=$?; echo "$0: Error on line "${LINENO}": ${BASH_COMMAND}"; exit $s' ERR

# Variables {{{
declare DOTFILES_HOME="${HOME}/.dotfiles"
declare THIS_EXEC="$(basename "${BASH_SOURCE[0]}")"

# Logging variables
declare LOG_TO_FILE=""
declare LOG_LEVEL=3
# }}}

# Imports {{{
. "${DOTFILES_HOME}/shell/common/source/common.sh" && src
# }}}

# Help Functions {{{
_help() {
  command cat <<EOF
${THIS_EXEC} | <insert description here>

USAGE:
  ${THIS_EXEC} [OPTIONS]

OPTIONS:
  -h | --help
    Print the help message (this message) and exit.
EOF
}
# }}}

# Setup/Cleanup Functions {{{
iu__install_basic_ubuntu_packages() {
  log_info "Installing Ubuntu packages required for bootstrapping"

  sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg \
    curl \
    sudo
}

iu__setup() {
  iu__install_basic_ubuntu_packages
}
# }}}

# Primary Functions {{{
iu__init_ubuntu_keyring() {
  log_info "Initializing Ubuntu keyring"

  # Google Cloud
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" |
    sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
}

iu__import_ubuntu_public_keys() {
  log_info "Importing Ubuntu public keys"

  # Google Cloud
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |
    sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
}

# The default PostgreSQL version included in the Ubuntu Package Archives is
# sure to be outdated. We can enable the PostgeSQL Apt Repository to get access
# to the latest and greatest versions.
#
# See the official docs for more information:
#   https://www.postgresql.org/download/linux/ubuntu/
iu__install_postgresql() {
  log_info "Installing base PostgreSQL packages"
  sudo apt install -y postgresql-common

  log_info "Enabling PostgreSQL Apt Repository"
  sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y

  log_info "Installing newest version of PostgreSQL"
  sudo apt install -y postgresql{,-client,-doc}
  sudo apt install -y libpq-dev
}

# PPAs are extra Ubuntu package archives that include newer packages that don't
# exist in the standard Ubuntu repository.
iu__add_ppas() {
  log_info "Adding Ubuntu PPAs"
  sudo add-apt-repository ppa:inkscape.dev/stable -y
  sudo add-apt-repository ppa:zhangsongcui3371/fastfetch -y
  sudo apt update
}

main() {
  print_header "Initializing Ubuntu Linux distribution"
  iu__setup
  iu__init_ubuntu_keyring
  iu__import_ubuntu_public_keys
  iu__add_ppas
  install_ubuntu_packages
  iu__install_postgresql
}
# }}}

# Parse CLI Options {{{
args=$(getopt -o h --long help -n 'init_ubuntu' -- "$@")
eval set -- "$args"

# extract options and their arguments into variables.
while true; do
  case "$1" in
  -h | --help)
    _help
    exit 0
    ;;

  --)
    shift
    break
    ;;

  *)
    err "Unknown option $1 to ${THIS_EXEC}"
    exit 2
    ;;
  esac
done
# }}}

main "${@}"

# vim:foldenable:foldmethod=marker:
