#!/usr/bin/env bash

# Trap errors and print error message
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Variables {{{
# Basic variables
declare DOTFILES_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
declare THIS_EXEC="$(basename "${BASH_SOURCE[0]}")"

# Polybar variables
declare POLYBAR_CONFIG_HOME="${HOME}/.config/polybar"

# Program flags
declare VERBOSE=false
declare LOG_TO_FILE="$DOTFILES_HOME/dotfiles.log"
# }}}

# Imports {{{
. "${DOTFILES_REPO}/shell/common/source/common.sh" && src
# }}}

# Functions {{{

# Help {{{
ipb__help() {
  cat <<EOF
${THIS_EXEC}

Initialize polybar configuration.

USAGE:
  ${THIS_EXEC} [OPTIONS]

OPTIONS:
  -h | --help
    Print the help message (this message) and exit.

  -v | --verbose
    Run with extra logging output.

  -t | --theme-number <NUMBER>
    Specify which optional polybar theme to install.
EOF
  exit 0
}
# }}}

ipb__init_polybar_config_dir() {
  log_info "Initializing polybar configuration directories"
  mkdir -p "${POLYBAR_CONFIG_HOME}/polybar.config.d"
}

ipb__main() {
  print_header "Initializing Polybar"
  ipb__init_polybar_config_dir
}
# }}}

# Parse CLI Options {{{
args=$(getopt -o hv \
  --long help,verbose \
  -n 'init_polybar' \
  -- "$@")
eval set -- "$args"

# extract options and their arguments into variables.
while true; do
  case "$1" in
  -v | --verbose)
    VERBOSE=true
    shift
    ;;

  -h | --help)
    ipb__help
    shift
    break
    ;;

  --)
    shift
    break
    ;;

  *)
    err "Unknown option $1 to ${THIS_EXEC}"
    exit 2
    ;;
  esac
done
# }}}

ipb__main

# vim:foldenable:foldmethod=marker:
