#!/usr/bin/env bash

# Trap errors and print error message
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Variables {{{
declare DOTFILES_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
declare THIS_EXEC="$(basename "${BASH_SOURCE[0]}")"

declare VERBOSE=false

declare MUTT_ATTACHMENTS_DIR="${HOME}/attachments"
declare MUTT_CONFIG_DIR="${DOTFILES_REPO}/link/mutt"
declare MUTT_CONFIG_TARGET="${HOME}/.mutt"
# }}}

# Imports {{{
. "${DOTFILES_REPO}/shell/common/source/common.sh"
# }}}

# Functions {{{
_help() {
  cat <<EOF
${THIS_EXEC}

<insert description here>

USAGE:
  ${THIS_EXEC} [OPTIONS]

OPTIONS:
  -h | --help
    Print the help message (this message) and exit.

  -v | --verbose
    Run with extra logging output.
EOF
  exit 0
}

make_directories() {
  mkdir -p "$MUTT_ATTACHMENTS_DIR"
}

link_mutt_config() {
  ln -sf "$MUTT_CONFIG_DIR" "$MUTT_CONFIG_TARGET"
}

main() {
  log_info "Initializing mutt..."
  make_directories
  link_mutt_config
  log_info "Done!"
}
# }}}

# Parse CLI Options {{{
args=$(getopt -o hvf --long help,verbose,full-install -n 'init_arch' -- "$@")
eval set -- "$args"

# extract options and their arguments into variables.
while true; do
  case "$1" in
  -v | --verbose)
    VERBOSE=true
    shift
    ;;

  -h | --help)
    _help
    shift
    break
    ;;

  --)
    shift
    break
    ;;

  *)
    err "Unknown option $1 to ${THIS_EXEC}"
    exit 2
    ;;
  esac
done
# }}}

main

# vim:foldenable:foldmethod=marker:
