#!/usr/bin/env bash

# Exit on error
set -e

# Variables {{{
declare DOTFILES_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# }}}

# Imports {{{
. "${DOTFILES_REPO}/shell/common/source/common.sh"
# }}}

# Variables {{{
declare NERD_FONTS_GIT_URL="https://github.com/ryanoasis/nerd-fonts.git"
declare NERD_FONTS_DEST_DIR="$WS/nerd-fonts"
# }}}

# Functions {{{
clone_nerd_fonts_repo() {
  git clone --depth 1 "${NERD_FONTS_GIT_URL}" "${NERD_FONTS_DEST_DIR}"
}

install_nerd_fonts() {
  pushd "$NERD_FONTS_DEST_DIR" &>/dev/null
  ./install.sh
  popd &>/dev/null
}

main() {
  log_info "Initializing Nerd Fonts"
  clone_nerd_fonts_repo
  install_nerd_fonts
  log_info "Done"
}
# }}}

main

# vim:foldenable:foldmethod=marker
