#!/usr/bin/env bash

# Trap errors and print error message
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Variables {{{
declare DOTFILES_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
declare THIS_EXEC="$(basename "${BASH_SOURCE[0]}")"

# Logging variables
declare LOG_TO_FILE=""
declare LOG_LEVEL=3

declare IMPORT="${DOTFILES_REPO}/bash/source"
# }}}

# Imports {{{
. "${IMPORT}/colors.bash"
. "${IMPORT}/functions_log.bash"
# }}}

# Functions {{{
_help() {
  cat <<EOF
${THIS_EXEC}

<insert description here>

USAGE:
  ${THIS_EXEC} [OPTIONS]

OPTIONS:
  -h | --help
    Print the help message (this message) and exit.
EOF
}

# This is very important. We should not proceed unless we actually have Docker
# installed on the system.
check_docker_installed() {
  log_info "Checking for working docker installation..."
  if [ ! -x "$(command -v docker)" ]; then
    err "Docker not installed."
    return 1
  fi
}

# In order for the main user to use Docker, they must first be added to the
# docker group.
add_user_to_docker_group() {
  log_info "Adding user to docker group..."
  sudo usermod -a -G docker "$(whoami)"
}

# Enable the Docker systemd service
enable_docker_service() {
  log_info "Enabling dockerd service..."
  if [ -x "$(command -v systemctl)" ]; then
    log_info "Enabling docker systemd service unit."
    sudo systemctl enable --now docker.service
  fi
}

main() {
  print_header "Initializing Docker Configuration"
  check_docker_installed && {
    add_user_to_docker_group
    enable_docker_service
  }
}
# }}}

# Parse CLI Options {{{
args=$(getopt -o h --long help-n 'init_<name_here>' -- "$@")
eval set -- "$args"

# extract options and their arguments into variables.
while true; do
  case "$1" in
  -h | --help)
    _help
    exit 0
    ;;

  --)
    shift
    break
    ;;

  *)
    err "Unknown option $1 to ${THIS_EXEC}"
    exit 2
    ;;
  esac
done
# }}}

main "${@}"

# vim:foldenable:foldmethod=marker:
