#!/usr/bin/env bash

# Prep the .vim dir and install Pathogen:
if [[ ! -f ~/.vim/autoload/pathogen.vim ]]; then
    mkdir -p ~/.vim ~/.vim/autoload ~/.vim/bundle
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

# Clone vim bundles:
#   Solarized, Fugitive, NERD TREE, Syntastic, Surround, CTRLP, NERD Commenter
pushd ~/.vim/bundle
    git init
    git add .
    git commit -m "First commit"

    username=""
    password=""
    answer=""
    vim_bundle_repo="vim-bundles"
    finished=false
    while [[ $finished == false ]]; do
        echo "Enter your GitHub username:" 1>&2
        read -r username
        echo "Enter your GitHub password (leave blank to be prompted later):" 1>&2
        read -rs password
        echo "You entered:" 1>&2
        echo -e "    Username: ${BLUE}$username${NC}" 1>&2
        echo -e "    Password: ${BLUE}$password${NC}" 1>&2
        echo "Is this correct? [y/n]" 1>&2
        read -sn 1 answer
        answer=${answer:-y}
        if [[ "$answer" =~ [Yy] ]]; then
            finished=true
        fi
    done

    repo_name_answer=""
    while [[ ! $repo_name_answer =~ [Yy] && ! $repo_name_answer =~ [Nn] ]]; do
        echo "Use the default name 'vim-bundles' for the bundle repository? [y/n] (default: y)" 1>&2
        read -sn 1 repo_name_answer
        repo_name_answer=${repo_name_answer:-y}
    done
    if [[ "$repo_name_answer" =~ [Nn] ]]; then
        echo "Enter the name for the vim bundle repository:" 1>&2
        read -r vim_bundle_repo
    fi

    # Create remote repository on GitHub
    if [[ "$password" != "" ]]; then
        curl -u "$username":"$password" "https://api.github.com/user/repos" -d "{\"name\":\"$vim_bundle_repo\"}" >> /dev/null
    else
        curl -u "$username" "https://api.github.com/user/repos" -d "{\"name\":\"$vim_bundle_repo\"}" >> /dev/null
    fi

    # Set the remote URL for the vim-bundles repo:
    git remote set-url origin "git@github.com:$username/vim-bundles.git"

    git submodule add git://github.com/altercation/vim-colors-solarized.git
    git submodule add git://github.com/tpope/vim-fugitive.git
    vim -u NONE -c "helptags vim-fugitive/doc" -c q
    git submodule add git://github.com/scrooloose/nerdtree.git
    git submodule add git://github.com/scrooloose/syntastic.git
    git submodule add git://github.com/tpope/vim-surround.git
    git submodule add git://github.com/kien/ctrlp.vim.git
    git submodule add git://github.com/scrooloose/nerdcommenter.git
    git submodule add git://github.com/airblade/vim-gitgutter.git
    git submodule add git://github.com/pangloss/vim-javascript.git
    git submodule add git://github.com/tpope/vim-rails.git
    git submodule add git://github.com/tpope/vim-bundler.git
    git submodule add git://github.com/mattn/emmet-vim.git
    git submodule add git://github.com/godlygeek/tabular.git
    git submodule add git://github.com:ervandew/supertab.git
popd