#!/usr/bin/env bash

# Trap errors and print error message
set -uo pipefail
trap 's=$?; echo "$0: Error on line "${LINENO}": ${BASH_COMMAND}"; exit $s' ERR

# Variables {{{
declare DOTFILES_HOME="${HOME}/.dotfiles"
declare THIS_EXEC="$(basename "${BASH_SOURCE[0]}")"

# Logging variables
declare LOG_TO_FILE="${LOG_TO_FILE:-''}"
declare LOG_LEVEL="${LOG_LEVEL:-3}"
# }}}

# Imports {{{
. "${DOTFILES_HOME}/shell/common/source/common.sh" && src
# }}}

# Functions {{{
_help() {
  command cat <<EOF
${THIS_EXEC} | Enable custom Systemd services

This script should only be run to initialize very minimal desktop environments,
such as simple window managers (bspwm, i3, etc.), but not for full DEs like
KDE, GNOME, or Xfce since they manage many of these services in their own
unique ways.

USAGE:
  ${THIS_EXEC} [OPTIONS]

OPTIONS:
  -h | --help
    Print the help message (this message) and exit.

  -q | --quiet
    Only print error messages.

  -v | --verbose
    Increase the quantity of debugging output. Useful for debugging. This option
    may be presented multiple times to further increase logging verbosity.
EOF
}

# Link a wallpaper changing script to `/usr/local/bin/change-wallpaper`
isd__link_change_wallpaper_script() {
  local changeWallpaperScript="${DOTFILES_HOME}/link/home/.fehbg"
  local scriptTarget="/usr/local/bin/change-wallpaper"

  log_info "Linking wallpaper changing script" \
    "${BLUE}${changeWallpaperScript}${NC} to ${BLUE}${scriptTarget}${NC}"

  if [ -f "${scriptTarget}" ]; then
    err "File ${BLUE}${scriptTarget}${NC} already exists"
    return 1
  fi

  sudo ln -sf "${changeWallpaperScript}" "${scriptTarget}"
}

# Enable/start custom Systemd units contained in the dotfiles repo.
isd__enable_custom_user_services() {
  systemctl --user daemon-reload
  log_info "Enabling change-wallpaper service"
  systemctl --user enable --now change-wallpaper.timer
}

# Enable global Systemd services.
isd__enable_system_services() {
  log_info "Enabling systemd-homed service"
  sudo systemctl enable --now systemd-homed.service
  log_info "Enabling ACPID service"
  sudo systemctl enable --now acpid.service
}

main() {
  print_header "Initializing custom Systemd services"
  isd__link_change_wallpaper_script
  isd__enable_custom_user_services
  isd__enable_system_services
}
# }}}

# Parse CLI Options {{{
args=$(getopt -o hqv \
  --long help,quiet,verbose \
  -n '<name_here>' \
  -- "$@")
eval set -- "$args"

# extract options and their arguments into variables.
while true; do
  case "$1" in
  -h | --help)
    _help
    exit 0
    ;;

  -q | --quiet)
    LOG_LEVEL=1
    shift
    ;;

  -v | --verbose)
    ((LOG_LEVEL += 1))
    shift
    ;;

  --)
    shift
    break
    ;;

  *)
    err "Unknown option $1 to ${THIS_EXEC}"
    exit 2
    ;;
  esac
done
# }}}

main "${@}"

# vim:foldenable:foldmethod=marker:
