#!/usr/bin/env bash

#  Setup / Cleanup {{{
# Performs initial setup.
setup() {
  log_info "Setting up...";
}

# Cleanup after the program finishes.
cleanup() {
  log_info "Cleaning up...";
}
trap cleanup EXIT
# }}}

# Primary Functions {{{
install_clang() {
  sudo apt-get install clang llvm;
}

main() {
  setup;
  install_clang;
}
# }}}

# Variable Definitions {{{
# Directories
declare DOTFILES_HOME="$HOME/.dotfiles";
declare DOTFILES_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)";
declare IMPORT="${DOTFILES_REPO}/source";
# }}}

# Imports {{{
source "${IMPORT}/functions_log.bash";
source "${IMPORT}/colors.bash";
# }}}

main;
