#!/usr/bin/env bash

# Trap errors and print error message
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Variables {{{
declare DOTFILES_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
declare THIS_EXEC="$(basename "${BASH_SOURCE[0]}")"

declare IMPORT="${DOTFILES_REPO}/bash/source"
# }}}

# Imports {{{
. "${IMPORT}/colors.bash"
. "${IMPORT}/functions_log.bash"
# }}}

# Functions {{{
_help() {
  cat <<EOF
${THIS_EXEC}

<insert description here>

USAGE:
  ${THIS_EXEC} [OPTIONS]

OPTIONS:
  -h | --help
    Print the help message (this message) and exit.
EOF
}

check_docker_installed() {
  if [ ! -x "$(command -v docker)" ]; then
    err "Docker not installed."
    return 1
  fi
}

add_user_to_docker_group() {
  sudo usermod -a -G docker
}

main() {
  print_header "Initializing Docker Configuration"
  check_docker_installed && {
    add_user_to_docker_group
  }
}
# }}}

# Parse CLI Options {{{
args=$(getopt -o h --long help-n 'init_<name_here>' -- "$@")
eval set -- "$args"

# extract options and their arguments into variables.
while true; do
  case "$1" in
  -h | --help)
    _help
    exit 0
    ;;

  --)
    shift
    break
    ;;

  *)
    err "Unknown option $1 to ${THIS_EXEC}"
    exit 2
    ;;
  esac
done
# }}}

main "${@}"

# vim:foldenable:foldmethod=marker:
