#!/usr/bin/env bash

# Trap errors and print error message
set -euo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Variables {{{
declare DOTFILES_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)";
declare THIS_EXEC="$(basename "${BASH_SOURCE[0]}")";

declare IMPORT="${DOTFILES_REPO}/bash/source";
declare VERBOSE=false;

# User's info directory for third party info manuals.
declare LOCAL_INFO_DIR="${HOME}/.local/share/info"
# }}}

# Imports {{{
source "${IMPORT}/colors.bash";
source "${IMPORT}/functions_log.bash";
# }}}

# Functions {{{
_help() {
  cat <<EOF
${THIS_EXEC}

Install extra Emacs info pages.

Requires a number of prerequisite tools:

- asciidoc
- docbook2x

USAGE:
  ${THIS_EXEC} [OPTIONS]

OPTIONS:
  -h | --help
    Print the help message (this message) and exit.

  -v | --verbose
    Run with extra logging output.
EOF
exit 0;
}

# Take care of setup logic.
setup() {
  log_info "Setting up"
  local other_docbook2texi="$(which "docbook2texi")"
  local regular_docbook2texi_bin="/usr/bin/docbook2x-texi"

  # Alias the docbook2texi command for compatibility with Debian.
  if [ "$(command -v "docbook2texi")" != "" ]; then
    alias docbook2x-texi="docbook2texi"
  else
    alias docbook2texi="docbook2x-texi"
  fi

  mkdir -p "${LOCAL_INFO_DIR}"
}

# Install info pages for the Git version control system.
install_git_info() {
  local git_info_url="https://github.com/git/git/archive/master.tar.gz"
  local git_info_dir="git-master"
  local git_info_tar="${git_info_dir}.tar.gz"
  local git_info_doc_dir="${git_info_dir}/Documentation"

  print_header "Installing Git Info Manual"
  wget -O "${git_info_tar}" "$git_info_url"
  tar -zxvf "$git_info_tar"
  (
    cd "${git_info_doc_dir}" || return 1
    make git.info gitman.info
    mv git.info gitman.info "${LOCAL_INFO_DIR}"
  )
  (
    cd "$LOCAL_INFO_DIR" || return 1
    install-info git.info dir
    install-info gitman.info dir
  )

  rm -f "${git_info_tar}"
  rm -rf "${git_info_dir}"
  succ "Done"
}

# Install info pages for the Python programming language.
install_python_info() {
  local python_info_url="https://github.com/python/cpython/archive/master.tar.gz"
  local python_info_tar="master.tar.gz"
  local cpython_dir="cpython-master"

  print_header "Installing Python Info Manual"
  wget -O "${python_info_tar}" "${python_info_url}"
  tar -zxvf "$python_info_tar"
  (
    cd "${cpython_dir}/Doc" || return 1
    sphinx-build -b texinfo -d build/doctrees . build/texinfo
    cd build/texinfo && make
    mv python.info "${LOCAL_INFO_DIR}"
  )
  (
    cd "${LOCAL_INFO_DIR}" || return 1
    install-info python.info dir
  )

  rm -f "${python_info_tar}"
  rm -rf "${cpython_dir}"
  succ "Done"
}

# Install info pages for the Perl programming language.
install_perl_info() {
  local perl_info_url="https://github.com/Perl/perl5.git"
  local perl_dir="perl"
  local base
  local txi

  print_header "Installing Perl Info Manual"
  git clone "${perl_info_url}" "${perl_dir}"
  (
    cd "${perl_dir}/pod" || return 1
    for pod in perl*.pod; do
      base="$(basename "${pod}" '.pod')"
      txi="${base}.texi"
      pod2texi "${pod}" > "${txi}" && makeinfo "${txi}"
    done
    touch perl-menu.info
    for info in *.info; do
      base="$(basename "${info}" '.info')"
      install-info --entry="* ${base}: (${info}). " --section=Perl "${info}" perl-menu.info
    done
    find . -maxdepth 1 -mindepth 1 -iname "*.info*" -exec mv -t "${LOCAL_INFO_DIR}" '{}' \;
  )
  (
    cd "${LOCAL_INFO_DIR}" || return 1
    install-info --entry="* Perl: (perl-menu.info). " --section=Perl perl-menu.info dir
  )

  rm -rf "${perl_dir}"
  succ "Done"
}

# Install info pages for GNU's standard C++ library.
install_stdlibpp_info() {
  print_header "Installing stdlib++ Info Manual"
  wget "http://www.netgull.com/gcc/infrastructure/libg%2B%2B-2.8.1.3.tar.gz"
  tar -xvf libg++-2.8.1.3.tar.gz libg++-2.8.1.3/libg++/texinfo/lgpl.texinfo
  tar -xvf libg++-2.8.1.3.tar.gz libg++-2.8.1.3/libg++/libg++.texi
  (
    cd libg++-2.8.1.3/libg++/
    cp texinfo/lgpl.texinfo .
    makeinfo libg++.texi
    cp libg++.info "${LOCAL_INFO_DIR}"
  )
  (
    cd "${LOCAL_INFO_DIR}" || return 1
    install-info libg++.info dir
  )
  succ "Done"
}

install_lisp_spec_info() {
  local cl_info_dir="/tmp/cl-info"
  local lisp_spec_url="ftp://ftp.gnu.org/pub/gnu/gcl/gcl.info.tgz"
  local lisp_spec_tar="gcl.tar.gz"

  print_header "Installing Lisp Spec Info Manual"
  mkdir -p "${cl_info_dir}"
  (
    cd "${cl_info_dir}" || return 1
    wget -O "${lisp_spec_tar}" "${lisp_spec_url}"
    mv info/* "${LOCAL_INFO_DIR}"
    install-info --section="Software development" \
      --entry="* HyperSpec: (gcl). Common Lisp HyperSpec." \
      "${LOCAL_INFO_DIR}/gcl.info" "${LOCAL_INFO_DIR}/dir"
  )
  succ "Done"
}

# Main entry point for the program.
main() {
  print_header "Installing Extra Emacs Info Manuals"
  setup
  # install_git_info
  # install_python_info
  install_perl_info
  # install_stdlibpp_info
  # install_lisp_spec_info
  succ "Successfully installed all info manuals"
}
# }}}

# Parse CLI Options {{{
args=$(getopt -o hvf --long help,verbose,full-install -n 'init_arch' -- "$@")
eval set -- "$args"

# extract options and their arguments into variables.
while true ; do
  case "$1" in
    -v | --verbose)
      VERBOSE=true;
      shift;
      ;;

    -h | --help)
      _help;
      shift;
      break;
      ;;

    --)
      shift;
      break
      ;;

    *)
      err "Unknown option $1 to ${THIS_EXEC}"
      exit 2
      ;;
  esac
done
# }}}

main "${@}";

# vim:foldenable:foldmethod=marker:
