#!/usr/bin/env bash

# Trap errors and print error message
set -Eeuo pipefail
trap 's=$?; echo "$0: Error on line "${LINENO}": ${BASH_COMMAND}"; exit $s' ERR

# Variables {{{
declare DOTFILES_HOME="${HOME}/.dotfiles"
declare THIS_EXEC="$(basename "${BASH_SOURCE[0]}")"

# Logging variables
declare LOG_TO_FILE=""
declare LOG_LEVEL=3
# }}}

# Imports {{{
. "${DOTFILES_HOME}/shell/common/source/common.sh" && src
# }}}

# Functions {{{
iasdf__help() {
  cat <<EOF
${THIS_EXEC}

asdf is a version manager for many languages, such as Java, Ruby, Python,
Erlang, Elixir, and many more. It's a one-stop-shop for managing programming
platforms on a project-by-project basis. You can think of asdf like rvm, nvm,
pyenv, and jenv all combined, but better!

USAGE:
  ${THIS_EXEC} [OPTIONS]

OPTIONS:
  -h | --help
    Print the help message (this message) and exit.
EOF
}

# Make sure ASDF executable is available before proceeding.
iasdf__check_asdf_exec_on_path() {
  if [ ! -x "$(command -v asdf)" ]; then
    err 'asdf executable not found on $PATH'
    return 1
  fi
}

iasdf__main() {
  print_header "Initializing ASDF Version Manager"
  (
    iasdf__check_asdf_exec_on_path &&
      add_asdf_plugins &&
      log_info "Done!"
  )
}
# }}}

# Parse CLI Options {{{
args=$(getopt -o h --long help -n 'init_<name_here>' -- "$@")
eval set -- "$args"

# extract options and their arguments into variables.
while true; do
  case "$1" in
  -h | --help)
    iasdf__help
    exit 0
    ;;

  --)
    shift
    break
    ;;

  *)
    err "Unknown option $1 to ${THIS_EXEC}"
    exit 2
    ;;
  esac
done
# }}}

iasdf__main "${@}"

# vim:foldenable:foldmethod=marker:
