#!/usr/bin/env bash

# Configure system to use oh-my-zsh

if [[ -f ~/.zshrc ]]; then
    echo "Backing up old .zshrc file"
    cp ~/.zshrc ~/.zshrc.orig
fi

ln -s $ZSH_DOTFILES/link/.zshrc ~/.zshrc
chsh -s /bin/zsh