#!/usr/bin/env bash

# Variables {{{
declare DOTFILES_HOME="${HOME}/.dotfiles"
declare NERD_FONTS_GIT_URL="https://github.com/ryanoasis/nerd-fonts.git"
declare NERD_FONTS_DEST_DIR
declare LOG_LEVEL=3
# }}}

# Imports {{{
. "${DOTFILES_HOME}/shell/common/source/common.sh"
# }}}

# Functions {{{

# Setup logic for this script.
setup() {
  # Set variables that could not be set before importing definitions.
  NERD_FONTS_DEST_DIR="$WS/nerd-fonts"
}

clone_nerd_fonts_repo() {
  git clone --depth 1 "${NERD_FONTS_GIT_URL}" "${NERD_FONTS_DEST_DIR}"
}

install_nerd_fonts() {
  if [ -d "${NERD_FONTS_DEST_DIR}" ]; then
    (
      cd "${NERD_FONTS_DEST_DIR}"
      ./install.sh
    )
  else
    err "Nerd fonts directory does not exist."
    return 1
  fi
}

main() {
  setup
  log_info "Initializing Nerd Fonts"
  clone_nerd_fonts_repo
  install_nerd_fonts
  log_info "Done"
}
# }}}

main

# vim:foldenable:foldmethod=marker
