#!/usr/bin/env bash

# Prep the .vim dir and install Pathogen:
if [[ ! -f ~/.vim/autoload/pathogen.vim ]]; then
    mkdir -p ~/.vim ~/.vim/autoload ~/.vim/bundle
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

# Clone vim bundles:
pushd ~/.vim/bundle
git init
git add .
git commit -m "First commit"
echo "Make sure to add a remote URL for the bundle repo later" 1>&2
git submodule add git://github.com/altercation/vim-colors-solarized.git
popd