# This file configures how programs are allowed to interface with GnuPG.

# Allow Emacs to prompt user for GPG passwords from the minibuffer, rather than
# in a GUI popup.
allow-emacs-pinentry
allow-loopback-pinentry