#!/usr/bin/env bash

# This is where all the magic happens! Just run this executable and follow
# the instructions.
#
# Exit codes:
#   1 - User chose to abort installation
#   2 - .dotfiles dir already exists

###########################################################################
##                                                                       ##
##                              Variables                                ##
##                                                                       ##
###########################################################################

export DOTFILES_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export COPY_DIR="$DOTFILES_HOME/copy"
export LINK_DIR="$DOTFILES_HOME/link"
export INIT_DIR="$DOTFILES_HOME/init"
export VENDORS="$DOTFILES_HOME/vendors"
SHELL_HOME=""

# Add bash binaries to PATH for use in the installation:
export PATH="$DOTFILES_HOME/bash/bin:$PATH"

###########################################################################
##                                                                       ##
##                         Supporting Functions                          ##
##                                                                       ##
###########################################################################

# Get permission from admin right at the beginning:
sudo -v

# Keep-alive: update existing `sudo` time stamp until the installer has finished:
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Preps the user's environment for the installation:
function prep() {
    # Use custom color aliases:
    source "$DOTFILES_HOME/bash/source/colors.bash"

    # Ask user to overwrite existing install if applicable:
    if [[ -d ~/".dotfiles" ]]; then
        existing_install
    fi

    pull_submodules
}

# Prompt user whether or not to overwrite an existing install:
function existing_install() {
    local response=""
    while [[ ! $response =~ [Yy] && ! $response =~ [Nn] ]]; do
        echo "It appears that a .dotfiles directory already exists in your" 1>&2
        echo "user home. Do you want to overwrite it?" 1>&2
        read -sn 1 response
    done

    if [[ "$response" =~ [Yy] ]]; then
        rm -rf ~/".dotfiles"
    else
        echo "Aborting" 1>&2
        exit 2
    fi
}

function pull_submodules() {
    echo "Ensuring that submodules are cloned..." 1>&2
    pushd "$DOTFILES_HOME"
    git submodule update --init --recursive
    popd
}

# Ask user for shell type:
function determine_shell() {
    echo "Which installation would you like?" 1>&2
    local shell_type="$(clean-menu "bash" "zsh" "EXIT")"

    if [[ "$shell_type" == "EXIT" ]]; then
        echo "Aborting" 1>&2
        exit 1
    else
        SHELL_HOME="$DOTFILES_HOME/$shell_type"
    fi

    echo "Ok, you want a ${BLUE}$shell_type${NC} installation" 1>&2
    chsh -s "/bin/$shell_type"
}

# Install depencies and prepare apps:
function init_step() {
    # Prep the locate database:
    "$INIT_DIR/init_locate"

    # Make sure that brew is installed and up-to-date:
    "$INIT_DIR/init_homebrew"

    # Get powerline ready:
    local response=""
    while [[ ! $response =~ [Yy] && ! $response =~ [Nn] ]]; do
        echo "Would you like to install powerline and all dependencies?" 1>&2
        echo "If not, you can always install later." 1>&2
        read -sn 1 response
        response=${response:-y}
    done
    if [[ "$response" =~ [Yy] ]]; then
        "$INIT_DIR/init_powerline"
    fi

    # Initialize Vim
    "$INIT_DIR/init_vim"
}

# Copy files:
function copy_step() {
    local copy_dir="$DOTFILES_HOME/copy"

    cp "$copy_dir/.vars" ~/.vars
    cp "$copy_dir/.dirs" ~/.dirs
    cp "$copy_dir/.path" ~/.path
    cp "$copy_dir/batcharge.py" ~/"bin/batcharge.py"
    cp "$copy_dir/online-check.sh" ~/"online-check.sh"

    if [[ -d "$DOTFILES_HOME/vendors/oh-my-zsh/themes" ]]; then
        cp "$copy_dir/tjtrabue.zsh-theme" "$DOTFILES_HOME/vendors/oh-my-zsh/themes/tjtrabue.zsh-theme"
    else
        echoe "It appears that the oh-my-zsh submodule hasn't been cloned."
        echo "Run 'git submodule update --init --recursive' from the .dotfiles" 1>&2
        echo "directory and copy tjtrabue.zsh-theme to oh-my-zsh/themes" 1>&2
    fi
}

# Link files:
function link_step() {
    local shell_link_dir="$SHELL_HOME/link"

    [[ ! -d ~/".config" ]] && mkdir ~/".config"

    ln -s "$LINK_DIR/powerline" "$HOME/.config/powerline"
    ln -s "$LINK_DIR/DotfileSnippets" \
        "$HOME/Library/Application Support/Sublime Text 3/Packages/User/DotfileSnippets"
    ln -s "$LINK_DIR/Preferences.sublime-settings" \
        "$HOME/Library/Application Support/Sublime Text 3/Packages/User/Prefences.sublime-settings"

    for f in "$shell_link_dir"/.[a-zA-Z]*; do
        ln -s "$f" "$HOME/$(basename $f)"
    done
}

# Prepare the last bits of the dev environment and reinvoke the login shell:
function finish() {
    unset COPY_DIR
    unset LINK_DIR
    unset INIT_DIR
    unset VENDORS
    exec $SHELL -i
}
trap finish EXIT

# Used for printing errors:
function echoe () { echo "${RED}ERROR${NC}: $@" 1>&2 ; }

# Used for printing warnings:
function echow () { echo "${YELLOW}WARNING${NC}: $@" 1>&2 ; }


###########################################################################
##                                                                       ##
##                             Main Program                              ##
##                                                                       ##
###########################################################################

# Get environment ready for the installation:
prep

# Get shell install type from the user:
determine_shell

# Init, copy, link files:
init_step
copy_step
link_step