#+TITLE:  Ace Navigation
#+AUTHOR: Tom Trabue
#+EMAIL:  tom.trabue@gmail.com
#+DATE:   2020-05-25
#+STARTUP: fold

Configuration for the fantastic ace modes, such as =ace-jump-mode= used to
quickly move around a buffer, or ace-window used as a replacement for =C-o=.

*NOTE:* =ace-jump-mode= is old and no longer maintained, so I recommend using
=avy= as a modern alternative. See =my-avy= for configuration details.

* Ace Window
Quick and easy window navigation, Ace style! This plugin extends the buffer
jumping system of =ace-jump-mode= to navigating between windows, as well.

#+begin_src emacs-lisp
  (use-package ace-window
    :general
    (general-def 'override
      ;; Remap C-o to the ace-window function
      [remap other-window] 'ace-window
      ;; Also use C-, to call ace-window
      "C-," 'ace-window)
    (my/evil-leader-def 'override
      "aa" 'ace-window)
    :custom
    ;; Set window selection keys to the home row ones.
    (aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)))
#+end_src

* Ace Link
Quickly follow links in =help-mode=, =info-mode=, =woman-mode=, =eww-mode=,
=compilation-mode=, and =custom-map-mode=.  Uses the =o= key by default to
select a link.

#+begin_src emacs-lisp
  (use-package ace-link
    :demand t
    :general
    ;; `C-c o' follows links in in `org-mode'
    (my/user-leader-def org-mode-map
      "o" 'ace-link-org)
    :config
    (ace-link-setup-default))
#+end_src

* Ace Popup Menu
Replaces the standard GUI popup menu (=x-popup-menu= by default) with something
more useful. Instead of the basic right-click menu we're all used to,
=ace-popup-menu= replaces our right-click with an ace-style menu that we
interact with via home row hotkeys.

#+begin_src emacs-lisp
  (use-package ace-popup-menu
    :demand t
    :config
    (ace-popup-menu-mode 1))
#+end_src
