#+TITLE:   Clojure Configuration/Plugins
#+AUTHOR:  Tom Trabue
#+EMAIL:   tom.trabue@gmail.com
#+DATE:    2020-05-25
#+STARTUP: fold

Integration for the awesome Clojure programming language.  Thanks, Rich! The
world needed another Lisp.

* clojure-mode
Major mode for editing Clojure files.

#+begin_src emacs-lisp
  (use-package clojure-mode
    :straight
    ;; Default straight recipe only includes the clojure-mode.el file for some
    ;; reason.
    (clojure-mode :type git :host github :repo "clojure-emacs/clojure-mode"
                  :files (:defaults))
    :init
    (add-hook 'clojure-mode-hook
              (lambda ()
                (let ((max-columns 100))
                  ;; The Common Lisp style guide recommends 100 columns max instead of 80 due to Lisp
                  ;; having longer, more descriptive names.
                  (setq-local fill-column max-columns
                              whitespace-line-column max-columns))))
    :config
    ;; Add extra syntax coloring (imprecise, but pretty)
    (require 'clojure-mode-extra-font-locking))
#+end_src

* clojure-ts-mode
A work-in-progress replacement major mode for =clojure-mode= and its variants,
=clojure-ts-mode= (and its companion major modes) provide Treesitter-enabled
syntax highlighting, indentation, and navigation.

** Prerequisites
- Install the [[https://github.com/sogaiu/tree-sitter-clojure][tree-sitter-clojure]] grammar,
- Ensure Emacs is version 29 or higher,
- Make sure Emacs has Treesitter support by checking the result of
  =(treesit-available-p)=

** =use-package= specification
#+begin_src emacs-lisp
  (use-package clojure-ts-mode
    :demand t
    ;; Only install when running Emacs 29 or higher built with Treesitter support
    :if (and (>= emacs-major-version 29) (treesit-available-p))
    :custom
    ;; Highlight entire rich `(comment ...)' expression with the comment font face
    (clojure-ts-comment-macro-font-lock-body t)
    ;; How to indent Clojure code:
    ;;   'semantic (default) -> tries to match clojure-mode and cljfmt indentation
    ;;   'fixed -> Simple indentation strategy outlined in a blog post by Tonsky.
    (clojure-ts-indent-style 'semantic)
    ;; Whether to make forms inside `(comment ...)' forms top-level forms for evaluation and
    ;; navigation
    (clojure-ts-toplevel-inside-comment-form t)
    ;; Whether to automatically remap all major modes formerly controlled by `clojure-mode' to `clojure-ts-mode'.
    (clojure-ts-auto-remap t)
    ;; Whether to use Markdown syntax to highlight doc strings.
    (clojure-ts-use-markdown-inline t)
    ;; The maximum column width for Clojure(Script) docstrings.
    ;; Defaults to the value of `fill-column'.
    (clojure-ts-docstring-fill-column 80)
    ;; :init
    ;; ;; Remap old Clojure(Script) major modes to new Treesitter-enabled modes
    ;; ;; NOTE: Manually remapping is no longer required since this package introduced the
    ;; ;;       `clojure-ts-auto-remap' custom variable.
    ;; (dolist (mapping '((clojure-mode       . clojure-ts-mode)
    ;;                    (clojurec-mode      . clojure-ts-clojurec-mode)
    ;;                    (clojurescript-mode . clojure-ts-clojurescript-mode)))
    ;;   (add-to-list 'major-mode-remap-alist mapping))
    )
#+end_src

* CIDER
An /extremely/ powerful IDE for Clojure similar to SLIME or SLY for Common
Lisp.

To start the CIDER REPL server, press =C-c C-x j j= or =C-c M-j= from inside a
Clojure buffer.

** CIDER's Performance
CIDER is a powerful IDE server for Emacs (or potentially any editor that
decides to implement CIDER's nREPL specification), but there are situations
where it can be sluggish. You know what I mean: either the REPL lags after an
input, or a keyboard shortcut that sends new code to CIDER hangs for an
extended period of time. These problems are common, but are also quite
fixable. Here a few tips for how to speed up CIDER.

*** Update CIDER
Make sure you are running the latest version of CIDER. Performance issues
are fixed frequently.

*** Wait a while after startup
Plain and simple. After CIDER starts up, wait a minute or two before
interacting with it. I've found that sometimes CIDER needs a moment to
startup fully.

** ClojureScript Development
CIDER handles ClojureScript projects just as well as it does standard Clojure
projects.

*** shadow-cljs
=shadow-cljs= is a phenomenal build tool for ClojureScript projects that
integrates the Clojure ecosystem with Node.js. To start an nREPL for your
=shadow-cljs= project, type =C-c M-J=, and select =shadow= as the project type
from the prompt. You will also need to select a build profile to run, which is
usually named =:app= for web application projects.

**** Autostarting your app with =cider-jack-in-cljs=
To start your project automatically upon jacking in, create a =.dir-locals.el=
file in your project's root directory with the following content:

#+begin_src emacs-lisp :tangle no
  ;; Replace :app with the name of your build.
  ((nil . ((cider-default-cljs-repl . shadow)
           (cider-shadow-default-options . ":app")
           (cider-shadow-watched-builds . (":app")))))
#+end_src

**** Troubleshooting
- If CIDER has trouble starting your =shadow-cljs= nREPL, it is most often a
  dependency issue. Double check that your NPM and CLJS dependencies are
  compatible with one another and installed correctly.

** Variables
#+begin_src emacs-lisp
  (defvar my/extra-cider-jack-in-deps '(("zprint/zprint" "RELEASE"))
    "AList of extra dependencies for CIDER to install upon jack-in.")
#+end_src

** Functions
#+begin_src emacs-lisp
  (defun my/cider-test-prompt-for-filters ()
    "Interactively prompt user for filters to apply to a test run."
    (interactive)
    (cider-test-run-loaded-tests 'prompt-for-filters))

  (defun my/cider-doc-or-fallback-doc-function (&optional arg)
    "Run `cider-doc', and if the call fails, run a fallback doc function.

  The optional prefix ARG is passed on to `cider-doc'.  See that function's
  documentation for more details."
    (interactive "P")
    (cond
     ((cider-current-connection)
      (cider-doc arg))
     (t
      (lsp-bridge-popup-documentation))))

  (defun my/cider-repl-prompt-function (namespace)
    "Return the CIDER REPL prompt for the current NAMESPACE."
    (format "%s➣ " (replace-regexp-in-string "\\." "｜" (cider-abbreviate-ns namespace)
                                             'fixed-case 'literal)))

  (defun my/cider-insert-sexp-at-point-in-repl (&optional arg)
    "Insert the s-expression at point into the CIDER REPL and switch to it.

  If invoked with prefix ARG, also evaluate the s-expression in the REPL."
    (interactive "P")
    (cider-insert-in-repl (cider-sexp-at-point) arg))
#+end_src

** =use-package= specification
#+begin_src emacs-lisp
  (use-package cider
    :after evil-collection
    :hook
    ((clojure-mode clojure-ts-mode) . cider-mode)
    :general
    (general-unbind cider-repl-mode-map
      ",")
    (general-def cider-repl-mode-map
      "M-;" 'cider-repl-handle-shortcut)
    (general-def 'normal cider-repl-mode-map
      "C-j" 'cider-repl-next-input
      "C-k" 'cider-repl-previous-input
      "C-r" 'cider-repl-history
      "K"   'my/cider-doc-or-fallback-doc-function)
    (general-def 'normal cider-repl-history-mode-map
      ;; Move backwards/forwards through REPL history with j and k
      "j" 'cider-repl-history-forward
      "k" 'cider-repl-history-previous)
    (general-def 'insert cider-repl-mode-map
      "C-j"        'cider-repl-next-input
      "C-k"        'cider-repl-previous-input
      "C-n"        'cider-repl-next-input
      "C-p"        'cider-repl-previous-input
      "C-r"        'cider-repl-history
      "C-RET"      'cider-repl-newline-and-indent
      "C-<return>" 'cider-repl-newline-and-indent)
    (my/evil-leader-def cider-repl-mode-map
      ","   'cider-repl-handle-shortcut
      "ee"  'cider-eval-last-sexp
      "eE"  'cider-eval-last-sexp-and-replace
      "ca"  'cider-apropos
      "cb"  'cider-repl-clear-buffer
      "cC"  'cider-classpath
      "cc"  'cider-repl-clear-output
      "cF"  'cider-repl-toggle-clojure-font-lock
      "cH"  'cider-repl-history
      "ch"  'cider-repl-shortcuts-help
      "cN"  'cider-ns-reload
      "cn"  'cider-repl-set-ns
      "cp"  'cider-repl-toggle-pretty-printing
      "cq"  'cider-quit
      "cR"  'cider-restart
      "cr"  'cider-ns-refresh
      "cT"  'cider-repl-require-repl-utils
      "ctF" 'my/cider-test-prompt-for-filters
      "ctn" 'cider-test-run-ns-tests
      "ctp" 'cider-test-run-project-tests
      "ctr" 'cider-test-show-report
      "cu"  'cider-undef
      "cx"  'cider-run
      "czv" 'cider-tap-sexp-at-point
      "czz" 'cider-tap-last-sexp)
    (my/evil-leader-def cider-mode-map
      "="   'cider-format-buffer
      "<"   'cider-eval-last-sexp
      ">"   'cider-eval-last-sexp-and-replace
      "ee"  'cider-eval-last-sexp
      "eE"  'cider-eval-last-sexp-and-replace
      "ca"  'cider-apropos
      "cC"  'cider-classpath
      "cD"  'cider-javadoc
      "cd"  'cider-doc
      "cI"  'cider-insert-region-in-repl
      "ci"  'my/cider-insert-sexp-at-point-in-repl
      "cjj" 'cider-jack-in
      "cjs" 'cider-jack-in-cljs
      "cN"  'cider-ns-reload
      "cn"  'cider-repl-set-ns
      "cq"  'cider-quit
      "cR"  'cider-restart
      "cr"  'cider-ns-refresh
      "cS"  'cider-sideloader-start
      "cta" 'cider-test-run-loaded-tests
      "ctF" 'my/cider-test-prompt-for-filters
      "ctn" 'cider-test-run-ns-tests
      "ctp" 'cider-test-run-project-tests
      "ctr" 'cider-test-show-report
      "cu"  'cider-undef
      "cx"  'cider-run
      "czv" 'cider-tap-sexp-at-point
      "czz" 'cider-tap-last-sexp)
    (my/user-leader-def cider-mode-map
      ;; Remap `C-c C-c' to a better evaluation function.
      "C-c" 'cider-eval-dwim
      ;; For some reason `cider-jack-in' doesn't have a default binding.
      ;; I like `C-c C-j'.
      "C-j" 'cider-jack-in)
    (general-def 'normal cider-mode-map
      "gs"              'cider-find-var
      "gi"              'cider-find-resource
      "gu"              'cider-xref-fn-refs
      [remap cider-doc] 'my/cider-doc-or-fallback-doc-function)
    ;; Clearing the whole REPL is a useful feature since the REPL gets slower
    ;; the larger it gets.
    (my/user-leader-def cider-repl-mode-map
      "M-b" 'cider-repl-clear-buffer)
    :custom
    ;; Which printing function CIDER uses under the hood to print output.
    ;; pprint (default): clojure.pprint/pprint
    ;; pr:               clojure.core/pr
    ;; fipp:             Fast Idiomatic Pretty Printer, which is 5-10 times faster
    ;;                   than pprint. Probably the best default choice.
    ;; puget:            Puget is canonical serialization of data on top of fipp,
    ;;                   but is slightly slower.
    ;; zprint:           Fast and flexible alternative to the libraries mentioned
    ;;                   above. Highly configurable, but requires you to specify
    ;;                   zprint as a depdency either in your cider jack-in init
    ;;                   command, or in your project dependencies file. I have also
    ;;                   noticed that zprint crashes when printing very large strings,
    ;;                   while fipp handles them far better.
    (cider-print-fn 'fipp)
    ;; The size in bytes of each chunk used for print streaming.
    ;; Smaller sizes mean smaller data chunks and faster feedback, but can lead
    ;; to inconsistent font-locking of output.
    (cider-print-buffer-size (* 4 1024))
    ;; Whether to show the large help message when the CIDER REPL opens.  Turning
    ;; it off saves space in the REPL buffer, which could speed up performance in
    ;; the beginning.
    (cider-repl-display-help-banner nil)
    ;; Set this to t if you want to see all debugging info for communication
    ;; between CIDER and the nREPL server in a buffer named *nrepl-messages
    ;; conn-name*. WARNING: This will greatly slow down CIDER!
    (nrepl-log-messages nil)
    ;; Whether to use font-locking for REPL input and results.
    (cider-repl-use-clojure-font-lock t)
    ;; How to colorize defined symbols of the following types.
    ;; Set this to nil to disable dynamic font-locking.
    ;; WARNING: Dynamic font-locking can slow down the REPL!
    ;;
    ;; NOTE 3/15/25: This option currently appears broken. Opening Clojure buffers with dynamic font
    ;; locking seems to disable font locking altogether. It may be due to a compatibility issue with
    ;; `clojure-ts-mode'. Try re-enabling dynamic font locking later and observe what happens.
    ;; (cider-font-lock-dynamically '(macro core deprecated function var))
    (cider-font-lock-dynamically nil)
    ;; (cider-font-lock-dynamically nil)
    ;; Whether to pretty-print REPL output
    (cider-repl-use-pretty-printing t)
    ;; Window startup behavior for the REPL.
    ;; 'display-only -> Do not focus the CIDER REPL when it starts up.
    (cider-repl-pop-to-buffer-on-connect 'display-only)
    ;; Prefix string for results of REPL evaluation
    (cider-repl-result-prefix " ➤ ")
    ;; The function returning the prompt string for the REPL.
    (cider-repl-prompt-function #'my/cider-repl-prompt-function)
    ;; Set character size limit for the REPL buffer.
    (cider-repl-buffer-size-limit 100000)
    ;; Wrap around REPL input history.
    (cider-repl-wrap-history t)
    ;; Max number of inputs held in history.
    (cider-repl-history-size 500)
    ;; File for storing CIDER REPL history.
    (cider-repl-history-file (locate-user-emacs-file "cider-repl-hist"))
    ;; Whether to display images in the REPL
    (cider-repl-use-content-types t)
    ;; String separating entries in the history buffer
    (cider-repl-history-separator
     ";; 🞜⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯🞜")
    ;; Turn off hover documentation since lsp-mode provides a better alternative.
    (cider-eldoc-display-for-symbol-at-point nil)
    ;; If set to t, CIDER will try to add expected function arguments based on the
    ;; current context (for example for the datomic.api/q function where it will
    ;; show the expected inputs of the query at point).
    (cider-eldoc-display-context-dependent-info t)
    ;; Whether to prefer local resources as opposed to remote, or TRAMP resouces,
    ;; if local resources are available.
    (cider-prefer-local-resources t)
    ;; Whether to save a file when CIDER loads its buffer.
    ;; 'prompt means to prompt, t means always save, nil means never save.
    (cider-save-file-on-load t)
    ;; Whether to enable a native JVMTI agent which makes eval interrupts work properly
    ;; on Java 21 and later.
    (cider-enable-nrepl-jvmti-agent t)
    ;; Whether to use the `enrich-classpath' program to add sources and JavaDocs to the classpath.
    ;; This option is super helpful in that it allows `cider-doc' to look up documentation for Java
    ;; classes and methods in the same way it looks up Clojure definitions.
    ;; Emacs requires no external configuration to use this option, but if you want to connect to
    ;; an external nREPL process using `cider-connect', refer to the documentation:
    ;; https://github.com/clojure-emacs/enrich-classpath
    ;; WARNING: Setting this to `t' appears to break `cider-jack-in' with an EOF error. This is
    ;; most likely an upstream issue. To get around this, use the Makefile configuration found
    ;; in the URL provided, and use `cider-connect' instead.
    (cider-enrich-classpath nil)
    ;; How to go about reusing dead CIDER REPLs when a new `cider-jack-in' or `cider-connect' command
    ;; is issued.
    (cider-reuse-dead-repls 'auto)
    :init
    (dolist (hook '(cider-mode-hook cider-repl-mode-hook))
      ;; Use fuzzy matching to display CIDER Company completions.
      (add-hook hook #'cider-company-enable-fuzzy-completion)
      (add-hook hook (lambda ()
                       ;; Disable LSP Company completion in clojure-mode because
                       ;; we want to use CIDER's completion instead since
                       ;; lsp-mode's completion has a problem: When you have the
                       ;; completion drop-down visible and you press backspace to
                       ;; delete characters, retyping those same characters you
                       ;; just deleted will no longer trigger Company's
                       ;; completions.
                       ;;
                       ;; Re-investigate this issue later and see if it still
                       ;; persists.
                       (when (bound-and-true-p lsp-completion-enable)
                         (setq-local lsp-completion-enable nil))
                       (when (bound-and-true-p lsp-bridge-mode)
                         (general-def 'normal cider-repl-mode-map
                           ;; We want to use CIDER's superior documentation lookup.
                           [remap lsp-bridge-popup-documentation] 'my/cider-doc-or-fallback-doc-function)))))
    ;; Turn on Enlighten feature for CIDER.  Enlighten evaluates definitions one
    ;; at a time, and it disables the use of C-c C-k.
    ;; NOTE: `cider-enlighten-mode' disables `cider-mode-map', which is frustrating.
    ;;       For this reason, I do not tend to enable `cider-enlighten-mode'.
    ;; (add-hook 'cider-mode-hook #'cider-enlighten-mode)
    ;; Extra CIDER REPL buffer configuration:
    (add-hook 'cider-repl-mode-hook
              (lambda ()
                ;; We still want `company-mode' in the CIDER REPL, even if we use `lsp-bridge'
                ;; completions in Clojure(Script) source code buffers.
                (company-mode 1)
                (when (bound-and-true-p lsp-bridge-mode)
                  (lsp-bridge-mode -1))))
    :config
    ;; Set default Clojure dependencies to inject upon jacking into the nREPL.
    ;; You must set these variables in :config instead of :custom due to a loading
    ;; order issue.
    ;;
    ;; NOTE: CIDER automatically adds all dependencies from
    ;;       `cider-jack-in-dependencies' to `cider-jack-in-cljs-dependencies'
    ;;       when jacking in, so there's no need to specify additional
    ;;       dependencies in both variables.
    (setq cider-jack-in-dependencies
          (delq nil
                (delete-dups
                 (append cider-jack-in-dependencies
                         my/extra-cider-jack-in-deps))))
    ;; Customize the CIDER REPL's face when we have fancy fonts installed.
    (when-let* ((fonts (font-family-list))
                (cider-repl-font (seq-find (lambda (f)
                                             (member f fonts))
                                           '("VictorMono Nerd Font" "Cascadia Code PL"))))
      (set-face-attribute
       'cider-repl-prompt-face nil
       :family cider-repl-font
       :weight 'bold
       :slant  'italic)))
#+end_src

** Plugins
*** cider-eval-sexp-fu
=eval-sexp-fu= extensions for CIDER. =eval-sexp-fu= provides tiny improvements to
expression evaluation - e.g. the expression you've just evaluated would briefly
flash, and other little enhancements.

Customizations are made via [[https://www.emacswiki.org/emacs/EvalSexpFu][eval-sexp-fu]].

#+begin_src emacs-lisp
  (use-package cider-eval-sexp-fu
    :after cider
    :demand t)
#+end_src

*** cider-storm
Cider Storm is an Emacs Cider front-end for the FlowStorm debugger with support
for Clojure and ClojureScript.

It brings the time-travel code stepping capabilities of FlowStorm to Emacs,
providing an interface similar to the Cider debugger one.

It also contains a bunch of utilities functions for interacting with FlowStorm.

Cider Storm isn't trying to re-implement the entire FlowStorm UI, but the most
used functionality. You can always start the full FlowStorm UI if you need the
extra tools.

#+begin_src emacs-lisp
  (use-package cider-storm
    :after cider
    :general
    (my/user-leader-def cider-mode-map
      "C-f" 'cider-storm-map)
    :init
    ;; Add flow-storm's middleware to the list of nREPL middleware packages to load when jacking in to
    ;; a CIDER session.
    ;; This setting may also be set in `.dir-locals.el' like so:
    ;; ((clojure-mode . ((cider-jack-in-nrepl-middlewares . ("flow-storm.nrepl.middleware/wrap-flow-storm"
  	;;                                                        ("refactor-nrepl.middleware/wrap-refactor" :predicate cljr--inject-middleware-p)
  	;;                                                         "cider.nrepl/cider-middleware")))))
    (add-to-list 'cider-jack-in-nrepl-middlewares "flow-storm.nrepl.middleware/wrap-flow-storm"))
#+end_src

*** kaocha-runner
An Emacs package for running Kaocha tests via CIDER.

Kaocha runner exposes the following commands:

- =kaocha-runner-run-test-at-point=: Runs the test at point in the current
  namespace.

- =kaocha-runner-run-tests=: Runs tests in the current namespace. With a prefix
  argument, it runs test id provided by the user.

- =kaocha-runner-run-all-tests=: Runs all tests in the project.

- =kaocha-runner-show-warnings=: If you get any warnings from Kaocha, the report
  will just say X warnings. You can display them with this command. Given a
  prefix argument, it displays the warnings in a separate window.

- =kaocha-runner-hide-windows=: When displaying results, kaocha-runner pops up a
  window. This command hides it again. You can also switch to the window and
  kill it normally, if you prefer that.

#+begin_src emacs-lisp
  (use-package kaocha-runner
    :after cider
    :general
    (my/user-leader-def cider-mode-map
      "k t" 'kaocha-runner-run-test-at-point
      "k r" 'kaocha-runner-run-tests
      "k a" 'kaocha-runner-run-all-test
      "k w" 'kaocha-runner-show-warnings
      "k h" 'kaocha-runner-hide-windows))
#+end_src

* clj-refactor
=clj-refactor= provides refactoring support for Clojure projects. It
complements the refactoring functionality you'd find in =clojure-mode= and
CIDER.

** Troubleshooting
*** =clj-refactor= and =refactor-nrepl= are out of sync
If you see this error when you jack into the CIDER nREPL, most likely the
problem is not with =clj-refactor= or its dependency =refactor-nrepl=, but with
your project's dependencies. Make sure that your Clojure, ClojureScript, and, if
necessary, Node.js dependencies are up-to-date and compatible and try again.

** =use-package= specification
#+begin_src emacs-lisp
  (use-package clj-refactor
    :delight
    :hook
    ((clojure-mode clojure-ts-mode) .
     (lambda ()
       (clj-refactor-mode 1)
       ;; This choice of keybinding leaves cider-macroexpand-1
       ;; unbound
       (cljr-add-keybindings-with-prefix "C-c C-j")))
    :custom
    ;; disable clj-refactor adding ns to blank files.
    ;; This is for interoperability with lsp-mode.
    ;; lsp-mode takes care of this task.
    (cljr-add-ns-to-blank-clj-files nil)
    ;; Whether to warn the user before parsing the AST.
    (cljr-warn-on-eval nil))
#+end_src
