#+TITLE:  Dev Ops Configuration/Plugins
#+AUTHOR: Tom Trabue
#+EMAIL:  tom.trabue@gmail.com
#+DATE:   2020-05-25
#+STARTUP: fold

Various dev-ops packages and configuration for Emacs. These tools enable
software deployment automation, testing, and maintenance.

* ansible
#+begin_src emacs-lisp
  (use-package ansible)
#+end_src

* docker
Emacs Docker integration with a Magit-style interface.

#+begin_src emacs-lisp
  (use-package docker
    :general
    (my/user-leader-def
      "d" 'docker))
#+end_src

* dockerfile-mode
Major mode for interacting with Dockerfiles.

#+begin_src emacs-lisp
  (use-package dockerfile-mode
    :mode "Dockerfile\\'")
#+end_src

* kubernetes.el
A Magit-style interface to the Kubernetes command-line client.
There is also a =kubernetes-evil= plugin for evil-mode support.
See =my-evil= for its configuration.

#+begin_src emacs-lisp
  (use-package kubernetes
    :commands kubernetes-overview)
#+end_src

* kubernetes-helm
Not to be confused with the narrowing completion framework, Helm is a Kubernetes
package manager, of sorts. It is a templating system for assembling different
aspects of an application release into one package that developers can customize
to suit their needs. =kubernetes-helm= provides Helm bindings for Emacs,
specifically to:

- update dependencies
- install a chart
- upgrade a chart
- get the values of a deployed chart
- get the status of a deployment
- render chart template locally

#+begin_src emacs-lisp
  (use-package kubernetes-helm
    :commands
    (kubernetes-helm-dep-up
     kubernetes-helm-install
     kubernetes-helm-upgrade
     kubernetes-helm-values
     kubernetes-helm-template))
#+end_src

* kele.el
Kele (kě lè, or kə-ˈlə) ("Kubernetes Enablement Layer for Emacs") is a
Kubernetes cluster management package. It empowers you to perform operations as
coarse or fine-grained as you need, fast, and get back to your work.

Kele comes with "batteries included." It contains several integrations with
noteworthy packages, e.g. Embark, that you can take advantage of in your own
configs.

To activate Kele, run =M-x kele-mode=, or add =(kele-mode 1)= to the package
configuration.

#+begin_src emacs-lisp
  (use-package kele
    :general
    (my/user-leader-def kele-mode-map
      "q" '(:keymap kele-command-map)))
#+end_src
