#+title:    Diagramming Plugins/Configuration
#+author:   Tom Trabue
#+email:    tom.trabue@gmail.com
#+date:     2021:08:19
#+property: header-args:emacs-lisp :lexical t
#+tags:
#+STARTUP: fold

Here you will find various plugins for generating and interacting with diagrams,
such as UML, sequence diagrams, class relationship diagrams, etc.

* mermaid-mode
Major mode for editing buffers written in Mermaid syntax for generating
diagram images. Requires the =mmdc= CLI executable to be installed, which is a
Node.js tool. Check the installation instructions for =mermaid-cli=.

** Functions

#+begin_src emacs-lisp
  (defun my/mermaid-get-bg-color ()
    "Get background color for Mermaid diagrams."
    ;; Use the main editor's default background color for Mermaid diagrams.
    (face-attribute 'default :background))

  (defun my/mermaid-determine-theme ()
    "Determine whether to use a light or dark theme for Mermaid diagrams."
    (let* ((theme "neutral")
           (bg (my/mermaid-get-bg-color))
           (luma (my-colors-calc-luma bg)))
      (if (< luma 128)
          "dark"
        "default")))
#+end_src

** use-package specification

#+begin_src emacs-lisp
  (use-package mermaid-mode
    :mode
    ;; Associate the .mmd and .mermaid extensions with mermaid-mode.
    ("\\.mmd$" "\\.mermaid$")
    :init
    (require 'my-colors)
    :custom
    ;; Where to find the mmdc, the mermaid command line tool.
    ;; You must have mmdc installed in order for mermaid-mode to work.
    (mermaid-mmdc-location (executable-find "mmdc"))
    ;; Should be ".png", ".pdf", or ".svg"
    (mermaid-output-format ".png")
    ;; Extra CLI flags to pass to mmdc.
    (mermaid-flags (concat "-b " (my/mermaid-get-bg-color)
                           " -t " (my/mermaid-determine-theme))))
#+end_src

* plantuml-mode
PlantUML plain-text specification for generating UML diagrams and much more. It
is a mature project, and has support for creating a multitude of diagram
types. Some of its supported diagram formats include:

- Sequence diagram
- Usecase diagram
- Class diagram
- Object diagram
- Activity diagram
- Component diagram
- Deployment diagram
- State diagram
- Timing diagram

#+begin_src emacs-lisp
  (use-package plantuml-mode
    ;; Activate plantuml-mode for files ending in .plantuml
    :mode "\\.plantuml\\'"
    :custom
    ;; Sample jar configuration:
    ;; (plantuml-jar-path "/path/to/your/copy/of/plantuml.jar")
    ;; (plantuml-default-exec-mode 'jar)
    ;; Sample executable configuration:
    (plantuml-executable-path (executable-find "plantuml"))
    (plantuml-default-exec-mode 'executable))
#+end_src
