#+TITLE:  Elixir Configuration/Plugins
#+AUTHOR: Tom Trabue
#+EMAIL:  tom.trabue@gmail.com
#+DATE:   2020-05-25
#+STARTUP: fold

Emacs plugins providing integration with Elixir, a functional programming
language built on Erlang's BEAM virtual machine optimized for writing
distributed, fault-tolerant applications that must contend with a vast multitude
of concurrent processes.

* elixir-ts-mode
The Tree-Sitter enabled version of =elixir-mode=.

#+begin_src emacs-lisp
  (use-package elixir-ts-mode
    :hook
    (elixir-ts-mode . (lambda ()
                        (push '(">=" . ?\u2265) prettify-symbols-alist)
                        (push '("<=" . ?\u2264) prettify-symbols-alist)
                        (push '("!=" . ?\u2260) prettify-symbols-alist)
                        (push '("==" . ?\u2A75) prettify-symbols-alist)
                        (push '("=~" . ?\u2245) prettify-symbols-alist)
                        (push '("<-" . ?\u2190) prettify-symbols-alist)
                        (push '("->" . ?\u2192) prettify-symbols-alist)
                        (push '("<-" . ?\u2190) prettify-symbols-alist)
                        (push '("|>" . ?\u25B7) prettify-symbols-alist))))
#+end_src

* elixir-mode (deprecated)
Major mode for working with Elixir files. =elixir-mode= provides font-locking,
indentation, and navigation support for the Elixir programming language.

NOTE: This package is for Emacs 29 and earlier. Starting with version 30, Emacs
comes with a built-in Elixir major mode with tree-sitter support. You should use
the built-in =elxir-mode= when possible.

#+begin_src emacs-lisp
  (use-package elixir-mode
    :if (<= emacs-major-version 29))
#+end_src

* mix.el
Minor mode for interacting with Mix (the Elixir build and lifecycle tool that
comes with each Elixir SDK) from inside Emacs.

To use mix, type the prefix key sequence (=C-c d= by default, but configurable
by changing the key sequence bound to =mix-minor-mode-command-map=), followed by
one of the following commands:

- =e=: =mix-execute-task=
- =d e=: =mix-execute-task= in an umbrella subproject.
- =t=: =mix-test=
- =d t=: =mix-test= in an umbrella subproject.
- =o=: =mix-test-current-buffer=
- =d o=: =mix-test-current-buffer= in an umbrella subproject.
- =f=: =mix-test-current-test=
- =d f=: =mix-test-current-test= in an umbrella subproject.
- =l=: =mix-last-command=

#+begin_src emacs-lisp
  (use-package mix
    :delight
    (mix-minor-mode nil mix)
    :hook
    ((elixir-mode elixir-ts-mode) . mix-minor-mode)
    :general
    (my/evil-leader-def mix-minor-mode-map
      "xe"  'mix-execute-task
      "xue" (lambda ()
              (interactive)
              (mix-execute-task nil 'use-umbrella-subprojects))
      "xl"  'mix-last-command
      "xt"  'mix-test
      "xut" (lambda ()
              (interactive)
              (mix-test nil 'use-umbrella-subprojects))
      "xo"  'mix-test-current-buffer
      "xuo" (lambda ()
              (interactive)
              (mix-test-current-buffer nil 'use-umbrella-subprojects))
      "xf"  'mix-test-current-test
      "xuf" (lambda ()
              (interactive)
              (mix-test-current-test nil 'use-umbrella-subprojects))))
#+end_src

* exunit.el
Simple interface for running ExUnit tests from inside Emacs.

#+begin_src emacs-lisp
  (use-package exunit
    :delight
    :hook
    ;; Turn on exunit-mode when editing Elixir files
    ((elixir-mode elixir-ts-mode) . exunit-mode))
#+end_src

* inf-elixir
Provides functions for opening and interacting with IEx, the Elixir REPL, from
inside Emacs. Useful if you do not use Alchemist, which is deprecated, so you
probably shouldn't.

#+begin_src emacs-lisp
  (use-package inf-elixir
    :general
    (my/user-leader-def elixir-ts-mode-map
      "i i" 'inf-elixir
      "i p" 'inf-elixir-project
      "i l" 'inf-elixir-send-line
      "i r" 'inf-elixir-send-region
      "i b" 'inf-elixir-send-buffer))
#+end_src

* Alchemist
A suite of tools for working with Elixir projects, including Phoenix MVC
applications.

*DEPRECATION NOTICE:* Much to the dismay of many an Elixirite, work on
Alchemist has halted indefinitely. As of now, the community is focusing all of
their efforts on =elixir-ls=, the Elixir LSP server. =elixir-ls= is an
amazing tool, one of the best language servers by far, but it lacks some of
the features of Alchemist. Thus, it is likely that a number of Alchemist
features will find new homes as their own projects on GitHub, so be on the
lookout.

#+begin_src emacs-lisp
  (use-package alchemist
    :disabled)
#+end_src
