#+title:  Elixir Configuration/Plugins
#+author: Tom Trabue
#+email:  tom.trabue@gmail.com
#+date:   2020:05:25
#+STARTUP: fold

Integration with Elixir, a functional, process-oriented programming language.

Needed for performance:
#+begin_src emacs-lisp :tangle yes
;; -*- lexical-binding: t; -*-

#+end_src

* elixir-mode
  The ubiquitous mode for working with Elixir files. =elixir-mode= provides
  font-locking, indentation, and navigation support for the Elixir programming
  language.

#+begin_src emacs-lisp :tangle yes
  (use-package elixir-mode)
#+end_src

* Alchemist
  =alchemist= is a suite of tools for working with Elixir projects, including
  Phoenix MVC applications.

  *DEPRECATION NOTICE:* Much to the dismay of many an Elixirite, work on
  Alchemist has halted indefinitely. As of now, the community is focusing all of
  their efforts on =elixir-ls=, the Elixir LSP provider. =elixir-ls= is an
  amazing tool, one of the best language servers by far, but it lacks some of
  the features of Alchemist. Thus, it is likely that a number of Alchemist
  features will find new homes as their own projects on GitHub, so be on the
  lookout!

#+begin_src emacs-lisp :tangle yes
  (use-package alchemist)
#+end_src
