#+title:  The Flycheck Syntax Checker
#+author: Tom Trabue
#+email:  tom.trabue@gmail.com
#+date:   2020:05:25

=flycheck= is a phenomenal general-purpose syntax checker based on a number of plugins.
=flycheck= comes pre-packaged with a huge number of language syntax plugins, so
it will probably work for you without any extra configuration. However, should
you need to install a few new =flycheck= plugins it is very simple to do.

Needed for performance:
#+begin_src emacs-lisp :tangle yes
;; -*- lexical-binding: t; -*-

#+end_src

* flycheck

#+begin_src emacs-lisp :tangle yes
  (use-package flycheck
    :hook
    ((prog-mode . (lambda ()
       ;; Enable flycheck mode by default when editing any programming language
       ;; file.
       (flycheck-mode)
       ;; Turn on the flyspell spell-checker for comments and strings.
       (flyspell-prog-mode)))
     ;; Check spelling in text documents as you type.
     (text-mode . flyspell-mode))
    :init
    ;; The allotted time before displaying errors at point.
    (setq flycheck-display-errors-delay 0.1))
#+end_src

* Plugins
** flycheck-cask
#+begin_src emacs-lisp :tangle yes
(use-package flycheck-cask
  :after (flycheck))
#+end_src

** flycheck-clojure

#+begin_src emacs-lisp :tangle yes
(use-package flycheck-clojure
  :after flycheck)
#+end_src

** flycheck-haskell
#+begin_src emacs-lisp :tangle yes
(use-package flycheck-haskell
  :after flycheck)
#+end_src

** flycheck-inline
   Shows Flycheck output inline right beneath their reporting location.  This is
   an alternative to =flycheck-pos-tip=. I tend to like =flycheck-pos-tip=
   better, though.

#+begin_src emacs-lisp :tangle yes
  ;; (use-package flycheck-inline
  ;;   :after (flycheck quick-peek)
  ;;   :hook
  ;;   (flycheck-mode . flycheck-inline-mode))
#+end_src

** flycheck-package
   Check Emacs Lisp packages for common errors.

#+begin_src emacs-lisp :tangle yes
  (use-package flycheck-package
    :after flycheck
    :config
    (flycheck-package-setup))
#+end_src

** flycheck-pkg-config
   Allows Flycheck to use =pkg-config= when determining C/C++ library headers.

#+begin_src emacs-lisp :tangle yes
  (use-package flycheck-pkg-config
    :after flycheck)
#+end_src

** flycheck-pos-tip
   Shows the error at point in a =pos-tip= graphical popup.

#+begin_src emacs-lisp :tangle yes
  (use-package flycheck-pos-tip
    :after flycheck
    :hook
    (flycheck-mode . flycheck-pos-tip-mode))
#+end_src

** flycheck-relint
   Checks regular expression syntax.

#+begin_src emacs-lisp :tangle yes
(use-package flycheck-relint
  :after flycheck
  :config
  (flycheck-relint-setup))
#+end_src

** flycheck-rust

#+begin_src emacs-lisp :tangle yes
(use-package flycheck-rust
  :after flycheck)
#+end_src

** flycheck-status-emoji
   Replaces standard Flycheck indicators with expressive emojis.

#+begin_src emacs-lisp :tangle yes
  (use-package flycheck-status-emoji
    :after flycheck
    :hook
    (flycheck-mode . flycheck-status-emoji-mode))
#+end_src
