#+title:  Code Folding Configuration/Plugins
#+author: Tom Trabue
#+email:  tom.trabue@gmail.com
#+date:   2020:05:26
#+STARTUP: fold

Here you will find plugins that allow Emacs to /fold/, or hide sections of code
away from sight in order to allow developers a glimpse of the bigger
picture. Folding sections of buffers help developers to focus on the parts
critical to their needs, removing extraneous paragraphs from sight. Emacs
supports a number of code folding /backends/, some of which come preinstalled
with Emacs, while still others must be installed as third-party plugins.

* origami
  =origami= is a smart code folding plugin for Emacs.

  As a rule, Emacs supports lots of different code folding minor modes, some of
  which are built-in, some are external plugins. =origami= is of the latter
  category, and is one of the best representatives.

  =origami= integrates nicely with =evil-mode=, so using standard Vim-like
  folding commands such as =zc= and =zo= work out of the box, no configuration
  necessary.

  #+begin_src emacs-lisp
    (use-package origami
      :hook
      (after-init . global-origami-mode))
  #+end_src

* vimish-fold
  =vimish-fold= adds Vim's native code folding capabilities to Emacs. My
  personal favorite code folding system.

  Please note that =vimish-fold= is /not/ a standard code folding backend for
  Emacs. That is, unlike =origami=, =vimish-fold= does not implement Emacs' code
  folding API in such a way that it can be used by standard folding functions,
  meaning that =vimish-fold= will not integrate with =evil-mode= by default. To
  get =evil-mode= to respect =vimish-fold= commands you will have to customize
  evil's keybindings. However, I find that I like to use =origami= for
  =evil-mode='s folding backend, and use =vimish-fold= as a secondary folding
  layer on top of =origami=. I only ever use =vimish-fold= to fold from mark
  symbols, and I use =origami= for everything else.

  #+begin_src emacs-lisp
    (use-package vimish-fold
      :hook
      ;; Activate vimish-fold mode for all buffers.
      ((after-init . vimish-fold-global-mode)
       ;; Re-create folds from mark comments when visiting a file.
       (find-file . vimish-fold-from-marks))
      :general
      (general-def
        ;; The standard vimish-fold keybinding. I don't tend to use it.
        "C-`" 'vimish-fold-toggle)
      (general-def 'normal
        "zf" 'vimish-fold-avy)
      (my/evil-leader-def
        "va" 'vimish-fold-avy
        "vd" 'vimish-fold-delete
        "vD" 'vimish-fold-delete-all
        "vf" 'vimish-fold
        "vm" 'vimish-fold-from-marks
        "vr" 'vimish-fold-refold
        "vR" 'vimish-fold-refold-all
        "vu" 'vimish-fold-unfold
        "vU" 'vimish-fold-unfold-all
        "vv" 'vimish-fold-toggle
        "vV" 'vimish-fold-toggle-all)
      :custom
      ;; Where to indicate a fold
      (vimish-fold-indication-mode 'right-fringe)
      ;; Whether to save folds on buffer saving.
      (vimish-fold-persist-on-saving t))
  #+end_src
