#+title: The Hydra Keyboard Macro System
#+author: Tom Trabue
#+email:  tom.trabue@gmail.com
#+date:   2020:5:25
#+STARTUP: fold

This file contains Plugins and configuration for the hydra hotkey macro package.

=hydra= is a system for defining a keybinding as a "gateway" to a group of
related keybindings that the user intends to press repeatedly. For instance, the
user could map =C-*= to the hydra for zooming the current window in and out with
the =j= and =k= keys. In fact, I define such a hydra in this file! To get rid of
(or slay) the hydra, the user merely has to hit any other key not defined within
the current hydra.  After that, the hydra disappears and the key the user
pressed to slay the hydra performs its normal function. Thus, if the user
activates the aforementioned zoom hydra with =C-*= and proceeds to zooms in and
out with the =j= and =k= keys, and then presses =p= to slay the hydra, then the
hydra disappears and =p= performs its usual operation for the prioritized
keymap.

* Hydras
** hydra-zoom
This is a simple, nearly trivial hydra used as an example and starting point for
creating more complex specimens. All that =hydra-zoom= accomplishes is defining
a zoom in/out hydra for the global keymap.

#+begin_src emacs-lisp
  (defun my/define-hydra-zoom ()
    "Wrapper function for defhydra hydra-zoom"

    ;; NOTE: This overrides the default `undo' keybinding.
    (defhydra hydra-zoom (global-map "C-/")
      "Zoom in/out in the current window:"
      ("k" text-scale-increase "in")
      ("j" text-scale-decrease "out")))
#+end_src

** hydra-resize-window
This hydra resizes the current window using VI keys.

#+begin_src emacs-lisp
  (defun my/define-hydra-resize-window ()
    "Wrapper function for defhydra hydra-resize-window."
    (defhydra hydra-resize-window (global-map "C-]")
      "Resize window with VI keys"
      ("h" shrink-window-horizontally "shrink horizontally")
      ("j" shrink-window "shrink vertically")
      ("k" enlarge-window "enlarge vertically")
      ("l" enlarge-window-horizontally "enlarge horizontally")))
#+end_src

** hydra-expand-region
This hydra expands and contracts the active region by semantic units using the
=expand-region= plugin.

#+begin_src emacs-lisp
  (defun my/define-hydra-expand-region ()
    "Wrapper function for defhydra hydra-expand-region."
    (defhydra hydra-expand-region (global-map "C-=")
      "Expand/contract visual region."
      ("=" er/expand-region "Expand region")
      ("-" er/contract-region "Contract region")))
#+end_src

* Activate hydras
#+begin_src emacs-lisp
  (defun my/define-hydras ()
    "Load custom hydra definitions."
    (interactive)
    (my/define-hydra-zoom)
    (my/define-hydra-resize-window)
    (my/define-hydra-expand-region))
#+end_src

* =use-package= specification
#+begin_src emacs-lisp
  (use-package hydra
    :after evil-collection
    :demand t
    :config
    (my/define-hydras))
#+end_src
