#+TITLE:  Haskell Configuration/Plugins
#+AUTHOR: Tom Trabue
#+EMAIL:  tom.trabue@gmail.com
#+DATE:   2020-05-25
#+STARTUP: fold

=haskell= may very well be the most beautiful programming language ever
created. It's not often that I look at a piece of code and go "Wow! How can
something so complicated look so simple?" Then again, it's one of the hardest
languages for young programmers to pick up, so there's that, too. But! Fear not,
for Emacs just so happens to be the best IDE for writing Haskell code. With the
incredible =haskell-mode= and =lsp-mode= features working together, Emacs will
strengthen your Haskell game in no time.

* haskell-mode
  The most important Haskell plugin for Emacs has to be =haskell-mode=. Far more
  than a simple syntax highlighter, =haskell-mode= provides integration with
  =ghci=, =stack=, =cabal=, and other Haskell tools, as well as =ghci='s
  built-in debugger.

#+begin_src emacs-lisp
  (use-package haskell-mode
    :after evil-collection
    :hook
    (haskell-mode . (lambda ()
                      ;; Used to integrate Emacs with
                      ;; inferior-haskell shells.
                      (interactive-haskell-mode)
                      ;; Enable declaration scanning mode for
                      ;; better menu support.
                      (haskell-decl-scan-mode)
                      ;; Insert a module template at the
                      ;; beginning of a new Haskell file.
                      (haskell-auto-insert-module-template)
                      ;; Automatically enable haskell-unicode
                      ;; input method.
                      (turn-on-haskell-unicode-input-method)))
    :general
    (general-def haskell-interactive-mode-map
      "M-k" 'haskell-interactive-mode-history-previous
      "M-j" 'haskell-interactive-mode-history-next
      ;; Jump to error at point
      "M-." 'haskell-mode-goto-loc)
    (my/user-leader-def haskell-interactive-mode-map
      ;; Show the type of the variable at point
      "C-t" 'haskell-mode-show-type-at)
    :custom
    ;; Format Haskell code when file is saved
    (haskell-stylish-on-save t)
    ;; (Re)generate tags file whenever code is saved
    (haskell-tags-on-save t)
    ;; Some handy and benign features
    (haskell-process-suggest-remove-import-lines t)
    (haskell-process-auto-import-loaded-modules t)
    (haskell-process-log t))
#+end_src

* structured-haskell-mode (shm)
   Structured Haskell Mode

   Not currently used because it's hard to get it to work globally.

#+begin_src emacs-lisp
;; (use-package shm
;;   :hook (haskell-mode . structured-haskell-mode)
;;   :config
;;   (haskell-indent-mode -1))
#+end_src

* ghci-completion
   =ghci= command completions for =inferior-haskell= buffers. The completion's
   appearance is very similar to that of the =fish= shell.

#+begin_src emacs-lisp
(use-package ghci-completion)
#+end_src
