#+TITLE:    Javascript Configuration/Plugins
#+AUTHOR:   Tom Trabue
#+EMAIL:    tom.trabue@gmail.com
#+DATE:     2021:07:16
#+TAGS:
#+STARTUP: fold

Javascript is perhaps the mode widely used programming language in the world
today. I don't like it, but it is important to be able to work with Javascript
in your favorite editor. This is my Emacs configuration for Javascript
integration.

* indium
  Indium is a fully featured Javascript development environment for Emacs. It is
  old, however, and newer Javascript development tools such as the TypeScript
  Language Server have obsoleted this project to a large extent.

  *NOTE:* Indium appears unmaintained on GitHub.

** Installation Instructions
   Indium runs on a client-server architecture. Thus, you need to install the
   server before you can run Indium from Emacs.  You need to run =npm install -g
   indium= to install the Indium server.

** =use-package= specification
   #+begin_src emacs-lisp
     (use-package indium
       ;; Indium appears unmaintained.
       :disabled)
   #+end_src

* npm-mode
  Build and run NPM projects from Emacs.

  #+begin_src emacs-lisp
    (use-package npm-mode)
  #+end_src

* rjsx-mode
  Major mode for editing JSX files.

  #+begin_src emacs-lisp
    (use-package rjsx-mode)
  #+end_src
