#+title:    Marginalia
#+author:   Tom Trabue
#+email:    tom.trabue@gmail.com
#+date:     2021:07:21
#+property: header-args:emacs-lisp :lexical t
#+tags:
#+STARTUP: fold

This package provides =marginalia-mode= which adds marginalia to the minibuffer
completions. Marginalia are marks or annotations placed at the margin of the
page of a book or in this case helpful colorful annotations placed at the margin
of the minibuffer for your completion candidates. Marginalia can only add
annotations to be displayed with the completion candidates. It cannot modify the
appearance of the candidates themselves, which are shown as supplied by the
original commands.

The annotations are added based on the completion category. For example
=find-file= reports the =file= category and =M-x= reports the =command=
category. You can cycle between more or less detailed annotators with the
command =marginalia-cycle=.

* use-package specification
  #+begin_src emacs-lisp :tangle yes
    (use-package marginalia
      :hook
      (after-init . marginalia-mode))
  #+end_src
