#+TITLE:   Org Mode Configuration (meta!)
#+AUTHOR:  Tom Trabue
#+EMAIL:   tom.trabue@gmail.com
#+DATE:    2020-05-26
#+STARTUP: fold

Org is one of Emacs' killer apps: a powerful ORGanizer and much more, Org
enables Emacs users to engage in /literate programming/, a method of software
development where engineers embed source code into explanatory, notebook-like
textual documents and evaluated as needed or all at once.

* org-bullets
Use fancy bullets in =org-mode=.

#+begin_src emacs-lisp
  (use-package org-bullets
    :after org
    :hook
    (org-mode . org-bullets-mode))
#+end_src

** org-beautify-theme
Remove colors from headings, and instead differentiate them by changing
their font size.

While very pretty, this theme can greatly slow down Emacs when editing an Org
buffer, so use with caution.

*IMPORTANT:* This theme *MUST* be loaded *AFTER* your primary Emacs theme!
Otherwise all of your =.org= files will look awful, with each heading
surrounded by big ugly boxes. See file =my-theme.org= for this theme's
activation.

#+begin_src emacs-lisp
  (use-package org-beautify-theme
    :after org
    :demand t)
#+end_src

* org-cliplink
=org-cliplink= is a simple function that takes a URL from the clipboard and
inserts an org-mode link into the current buffer, the title of which comes from
the page title found from the URL. It's a little limited, but it's handy for
getting URLs into an Org document, which you can edit later.

#+begin_src emacs-lisp
  (use-package org-cliplink
    :after org
    :general
    (my/user-leader-def org-mode-map
      "L" 'org-cliplink))
#+end_src

* org-roam
=org-roam= is an amazing plugin that integrates some of Roam's advanced note
taking features into =org-mode=. =org-roam= depends on a custom SQLite
database running behind the scenes to support its intelligent,
non-hierarchical note system. However, if you have a standard C compiler
installed, such as =gcc= or =clang=, =org-roam= will compile the database
automatically.

You will need to install the =graphviz= suite of tools in order to use
=org-roam='s graph functionality.

Because =org-roam='s nodes are just Org files, you can check your =org-roam=
database into your favorite version control system. Once pulled down,
=org-roam= will completely recreate your database from the metadata in your
repository. [[https://github.com/tjtrabue/roam-notes][I keep my org-roam database on GitHub]].

** Variables
#+begin_src emacs-lisp
  (defvar my/org-roam-dir (file-truename (concat user-emacs-directory "roam-notes"))
    "The directory acting as my `org-roam' database.")
#+end_src

** =use-package= specification
#+begin_src emacs-lisp
  (use-package org-roam
    :after (emacsql org)
    :demand t
    :general
    (my/user-leader-def
      "n c" 'org-roam-capture
      "n f" 'org-roam-node-find
      "n g" 'org-roam-graph   ; Need graphviz tools to generate/view graph.
      "n i" 'org-roam-node-insert
      "n l" 'org-roam-buffer-toggle
      ;; Dailies
      "n j" 'org-roam-dailies-capture-today)
    :custom
    ;; Set the path to the org-roam directory.
    (org-roam-directory my/org-roam-dir)
    ;; Automatically treat completion-at-point candidates as possible org-roam
    ;; node names.
    (org-roam-completion-everywhere t)
    :init
    ;; Acknowledge that we've upgraded from v1 to v2.
    (setq org-roam-v2-ack t)
    ;; I have my roam-notes directory checked in as a git repository on GitHub.
    ;; (make-directory org-roam-directory t)
    :config
    ;; Automatically keep org roam session synchronized.
    (org-roam-db-autosync-enable))
#+end_src

* org-super-agenda
Improved Org agenda that allows you to break your agenda items up into
sections.

#+begin_src emacs-lisp
  (use-package org-super-agenda
    :after org)
#+end_src

* org-download
Utility for moving downloaded images into Org buffers.

#+begin_src emacs-lisp
  (use-package org-download
    :after org
    :hook
    ;; Enable org-download in dired-mode.
    (dired-mode . org-download-enable)
    :init
    (setq-default org-download-image-dir
                  (file-truename (concat (getenv "HOME") "/images/org")))
    :config
    (make-directory org-download-image-dir t))
#+end_src

* org-preview-html
Preview org files in Emacs rendered as HTML.

#+begin_src emacs-lisp
  (use-package org-preview-html
    :after org)
#+end_src

* org-tree-slide
Give beautiful presentations from regular Org mode buffers! This is a
must-have plugin for the Org enthusiast.

To get started, =M-x org-tree-slide-mode=, and then use =C->= and =C-<= to
navigate slides.

#+begin_src emacs-lisp
  (use-package org-tree-slide
    :hook
    ;; Set the default profile for org-tree-slide-mode
    ;; Pre-defined profiles are simple, presentation, and TODO pursuit with
    ;; narrowing.
    (org-tree-slide-mode . org-tree-slide-presentation-profile)
    :general
    (general-def 'normal org-tree-slide-mode-map
      "C->" 'org-tree-slide-move-next-tree
      "C-<" 'org-tree-slide-move-previous-tree))
#+end_src

* ob-mermaid
Generate mermaid diagrams from =org-babel= source blocks. Adding a source
block is easy. Simple guard your mermaid code with a code block similar to
this: =#+begin_src mermaid :file output_file.png=

Supports the following properties:

- =file= - Output file. It should be either *svg*, *png* or *pdf*.
- =width= - Width of the page (Optional).
- =height= - Height of the page (Optional).
- =theme= - Theme of the chart, could be default, forest, dark or
  neutral (Optional).
- =background-color= - Background color. Example: transparent, red,
  ‘#F0F0F0’ (Optional).
- =mermaid-config-file= - JSON configuration file for mermaid (Optional).
- =css-file= - CSS file for the page (Optional).
- =pupeteer-config-file= - JSON configuration file for puppeteer (Optional).

#+begin_src emacs-lisp
  (use-package ob-mermaid
    :after (htmlize org)
    :custom
    (ob-mermaid-cli-path (executable-find "mmdc")))
#+end_src

* ox-gfm
This is a small exporter based on the Markdown exporter already existing in
Org mode.

#+begin_src emacs-lisp
  (use-package ox-gfm
    :after org
    :demand t
    :config
    (require 'ox-gfm nil t))
#+end_src

* org-ql
This package provides a query language for Org files. It offers two syntax
styles: Lisp-like sexps and search engine-like keywords.

It includes three libraries: The =org-ql= library is flexible and may be used as
a backend for other tools. The libraries =org-ql-search= and =helm-org-ql= (a
separate package) provide interactive search commands and saved views.

=org-ql= is a /very/ feature-rich package, and quite complex. It takes some time
to learn, but if you make prolific use of Org mode, =org-ql= can be a
game-changer.

#+begin_src emacs-lisp
  (use-package org-ql
    :after org)
#+end_src

* org-sticky-header
Keep the =org-mode= header for the current section at the top of the buffer.

#+begin_src emacs-lisp
  (use-package org-sticky-header
    :hook
    (org-mode . org-sticky-header-mode)
    :custom
    ;; How to display the sticky header. Can be one of:
    ;;   nil
    ;;   'full (show full path to the current heading)
    ;;   'reversed (show full path to current heading but in reverse order)
    (org-sticky-header-full-path 'full)
    ;; The prefix string for the sticky header-line.
    (org-sticky-header-heading-star "◉"))
#+end_src

* org-trello
=org-trello= is a minor mode that synchronizes org-mode buffers and a Trello
board. It has [[https://org-trello.github.io/][copious documentation online at its website]], so please check it
out for more details.

#+begin_src emacs-lisp
  (use-package org-trello
    :after org)
#+end_src

* org-web-tools
A library of Org mode functions for inserting copied URLs into Org buffers,
processing HTML into Org syntax, and much more. A very powerful package!

*NOTE:* This package depends on the Pandoc executable for many of its features.

#+begin_src emacs-lisp
  (use-package org-web-tools)
#+end_src
