#+title:    Perspective: Named Workspaces for Emacs
#+author:   Tom Trabue
#+email:    tom.trabue@gmail.com
#+date:     2021:07:22
#+property: header-args:emacs-lisp :lexical t
#+tags:
#+STARTUP: fold

=perspective.el= is a workspace management package for Emacs. It provides
facilities for grouping buffers and windows into named "perspectives" that you
can save and load at will.

To interact with =perspective.el=, type the command prefix (detailed in the
=use-package= specification below), and then observe the =which-key= guide for a
list of available commands. These commands include adding a buffer to the
current perspective, removing a buffer from the perspective, switching to a
different perspective, and many more.

* perspective.el vs persp-mode package
  You may be wondering why there are two different packages offering the
  =persp-mode= global minor mode. There's =perspective.el=, and then there's a
  package just called =persp-mode=. =persp-mode= the package is a /fork/ of
  =perspective.el= that has fallen behind and lost momentum. It was originally
  intended to make =perspective.el= easier to work with, especially with
  multiple frames, but it is less configurable and can be frustrating since it
  seizes control of Emacs in some invasive ways.

* =use-package= specification
  #+begin_src emacs-lisp
    (use-package perspective
      :after evil-collection
      :demand t
      :hook
      ;; Save perspective to disk whenever the user kills Emacs.
      (kill-emacs . persp-state-save)
      :bind-keymap
      ;; May be necessary to tie keybinding to perspective prefix
      ("C-c j" . perspective-map)
      :general
      (general-def 'override
        "C-x b" 'persp-switch-to-buffer
        "C-x k" 'persp-kill-buffer*
        "C-e" 'persp-switch-to-buffer)
      ;; Set evil-leader keys for perspective.el
      (my/evil-leader-def
        ;; Remappings of standard evil-leader shortcuts
        "bb" 'persp-switch-to-buffer
        "kk" 'persp-kill-buffer*
        ;; Custom perspective evil-leader shortcuts
        "pL" 'persp-state-load
        "pS" 'persp-state-save
        "pa" 'persp-add-buffer
        "pb" 'persp-switch-to-buffer*
        "pc" 'persp-kill
        "pi" 'persp-import
        "pk" 'persp-remove-buffer
        "pn" 'persp-next
        "pp" 'persp-prev
        "pr" 'persp-rename
        "ps" 'persp-switch)
      :custom
      ;; Prefix for all perspective.el commands
      (persp-mode-prefix-key (kbd "C-c j"))
      ;; Where perspective.el saves its configuration
      (persp-state-default-file
       (file-truename (concat user-emacs-directory "/persp-state.el")))
      :config
      ;; Turn on persp-mode globally
      (persp-mode 1)
      ;; Automatically resume the main perspective after x seconds.  The delay is
      ;; necessary to allow Emacs time to initialize before resuming the previous
      ;; perspective.
      (run-with-timer 3 nil #'persp-state-load persp-state-default-file))
  #+end_src

* Plugins
** persp-projectile
   Integrates =perspective.el= with =projectile=, allowing you to switch between
   perspectives specifically for Projectile projects. This is very similar to
   the standard =projectile-switch-project= function.

   #+begin_src emacs-lisp
     (use-package persp-projectile
       :after (perspective projectile)
       :general
       (general-def projectile-command-map
         [remap projectile-switch-project] 'projectile-persp-switch-project
         "," 'projectile-persp-switch-project))
   #+end_src
