#+title:    Perl Configuration/Plugins
#+author:   Tom Trabue
#+email:    tom.trabue@gmail.com
#+date:     2020:08:18
#+property: header-args:emacs-lisp :lexical t
#+tags:     perl raku

Here's my Perl configuration for Emacs.

#+begin_src emacs-lisp :tangle yes
;; -*- lexical-binding: t; -*-

#+end_src

* PDE
  PDE is a collection of Emacs Lisp modules for interacting with Perl code
  distributed through CPAN in a package named =Emacs::PDE=. Thus, you must
  install =Emacs::PDE= through your CPAN install utility, usually =cpanm=. Once
  you have installed PDE, you may load it in Emacs.

  *NOTE*: I do not recommend you use PDE right now as it can hijack a number of
  different configuration settings, such as =helm=.

#+begin_src emacs-lisp :tangle yes
;; Add the Elisp code in the PDE directory to load-path.
(let ((pde-dir (concat user-emacs-directory "pde")))
  (when (file-directory-p pde-dir)
    (add-to-list 'load-path pde-dir)))

(defun load-pde ()
  "Load the Perl Development Environment."
  (interactive)
  (let* ((pde-dir (concat user-emacs-directory "pde"))
         (pde-load-file (concat pde-dir "/pde-load.el")))
    (when (file-exists-p pde-load-file)
      (load pde-load-file))))

(define-minor-mode pde-mode
  "Minor mode for activating the Perl Development Environment package from CPAN."
  :lighter " PDE")
#+end_src

* Plugins
** cperl-mode
   =cperl-mode= is a more advanced Perl editing mode than the standard
   =perl-mode=.

#+begin_src emacs-lisp :tangle yes
  (use-package cperl-mode
    :config
    ;; Add cperl-mode to auto-mode-alist for editing perl files.
    (mapc (lambda (pair)
        (if (eq (cdr pair) 'perl-mode)
            (setcdr pair 'cperl-mode)))
      (append auto-mode-alist interpreter-mode-alist))
    ;; Get rid of troublesome keybindings
    (unbind-key (kbd "C-j") 'cperl-mode-map))
#+end_src

** perly-sense-mode
  PerlySense is an IDE backend for Perl. It interfaces with Emacs quite nicely.
  Much like PDE, You must install PerlySense via CPAN from the Devel::PerlySense
  package.

#+begin_src emacs-lisp :tangle yes
  (use-package perly-sense-mode
    :straight
    (perly-sense-mode :type git :host github :repo "tjtrabue/perly-sense-mode")
    :after cperl-mode
    :hook ((cperl-mode perl-mode) . perly-sense-mode)
    :init
    ;; The PerlySense prefix key (unset only if needed)
    (global-unset-key (kbd "C-c C-o"))
    (setq ps/key-prefix (kbd "C-c C-o"))
    ;; Load flymake if t
    (setq ps/load-flymake nil)
    :config
    (install-perly-sense))
#+end_src

** plsense
   Much like =company-plsense=, this is another Emacs interface plugin for
   =plsense=, but while =company-plsense= focuses on automatically completing
   what you type, this one provides other IDE features, such as
   jump-to-definition.

#+begin_src emacs-lisp :tangle yes
  (use-package plsense
    :after cperl-mode
    :hook
    ((cperl-mode perl-mode) . (lambda ()
      ;; Start the plsense servers automatically.
      (plsense-server-start)))
    :init
    ;; Key binding
    (setq plsense-popup-help-key "C-:")
    (setq plsense-display-help-buffer-key "M-:")
    (setq plsense-jump-to-definition-key "C-k")
    :config
    (plsense-config-default))
#+end_src
