#+title:    Smartparens: Automatic Delimiter Insertion
#+author:   Tom Trabue
#+email:    tom.trabue@gmail.com
#+date:     2021:03:10
#+property: header-args:emacs-lisp :lexical t
#+tags:
#+STARTUP: fold

=smartparens= is a very popular Emacs plugin that automatically inserts closing
delimiters based on the syntax of the programming language currently in
use. However, =smartparens= can do much more than simply insert closing
delimiters. It can act as a whole editing environment for Lisp dialects similar
to ParEdit. You can think of it like =vim-surround= and =vim-endwise= put
together plus a bunch of language-aware features that neither of the
aforementioned Vim plugins have.

* Notes on =smartparens-mode= and =smartparens-strict-mode=
  This package contains two minor modes for managing delimiters:
  =smartparens-mode= and =smartparens-strict-mode=. =smartparens-mode= does not
  enforce balanced delimiters, whereas =smartparens-strict-mode= does.

* =use-package= specification

  #+begin_src emacs-lisp
    (use-package smartparens
      :demand t
      :hook
      ;; Enable strict mode for Lisp dialects.
      ((cider-repl-mode
        clojure-mode
        emacs-lisp-mode
        ielm-mode
        lisp-mode
        lisp-interaction-mode
        sly-mrepl-mode)
       . smartparens-strict-mode)
      :config
      (require 'smartparens-config)
      ;; Always use smartparens.
      (smartparens-global-mode))
  #+end_src
