#+TITLE:   Spell Checking and Grammar Plugins
#+AUTHOR:  Thomas Trabue
#+EMAIL:   tom.trabue@gmail.com
#+DATE:    2024-11-23
#+TAGS:    spellcheck spelling spell grammar
#+STARTUP: fold

Emacs is a prose editor as well as a code editor, a task which greatly benefits
from having fast, flexible spell-checking.

* flyspell
=flyspell= is =flycheck='s companion spell-checker plugin. Where =flycheck=
checks for code correctness, =flyspell= checks spelling in both the traditional
and in a more coding-correct sense (i.e., take camel case into account, and so
on).

*NOTE:* =flyspell-mode= requires you to have an ispell-compatible spell-checking
binary installed, such as =hunspell=. Furthermore, =hunspell= requires you to
have dictionaries installed in predictable locations. Run =hunspell -D= to view
the path =hunspell= uses to find dictionaries, which is different depending on
your operating system.

** =use-package= specification
#+begin_src emacs-lisp
  (use-package flyspell
    ;; Currently using Jinx, which is newer and faster.
    :disabled
    ;; :hook
    ;; NOTE: Activating `flyspell-mode' or `flyspell-prog-mode' can really slow down editing.
    ;; ((prog-mode . flyspell-prog-mode)
    ;;  (text-mode . flyspell-mode))
    :init
    (setq ispell-program-name
          ;; Prefer aspell over hunspell since aspell is faster
          (if (executable-find "aspell") "aspell" "hunspell"))
    (cond ((equal ispell-program-name "hunspell")
           ;; Extra configuration for hunspell.
           (setq ispell-local-dictionary "en_US")
           (setq ispell-local-dictionary-alist
                 ;; Please note the list `("-d" "en_US")` contains ACTUAL
                 ;; parameters passed to hunspell You could use `("-d"
                 ;; "en_US,en_US-med")` to check with multiple dictionaries
                 '(("en_US" "[[:alpha:]]" "[^[:alpha:]]" "[']" nil
                    ("-d" "en_US") nil utf-8)))
           ;; New variable `ispell-hunspell-dictionary-alist' is defined in Emacs.
           ;; If it's nil, Emacs tries to automatically set up the dictionaries.
           (when (boundp 'ispell-hunspell-dictionary-alist)
             (setq ispell-hunspell-dictionary-alist ispell-local-dictionary-alist)))
          ((equal ispell-program-name "aspell")
           ;; Extra configuration for aspell.
           (setq ispell-extra-args '("--sug-mode=ultra" "--lang=en_US"))
           ;; Handle camel-case words
           (cond ((string-match-p "--camel-case"
                                  (shell-command-to-string "aspell --help"))
                  (add-to-list 'ispell-extra-args "--camel-case" t))
                 (t
                  ;; Older versions of aspell used --run-together instead of
                  ;; --camel-case
                  (add-to-list 'ispell-extra-args "--run-together" t)
                  (add-to-list 'ispell-extra-args "--run-together-limit=16" t)))))
    :config
    (ispell-set-spellchecker-params))
#+end_src

** flyspell-correct
Correct misspelled words using your favorite completion interface.

#+begin_src emacs-lisp
  (use-package flyspell-correct
    ;; Flyspell is currently disabled in favor of Jinx.
    :disabled
    :after flyspell
    :general
    (general-def flyspell-mode-map
      "C-." 'flyspell-correct-wrapper))
#+end_src

* Jinx
Jinx is a fast, just-in-time spell-checker for Emacs. Jinx highlights misspelled
words in the text of the visible portion of the buffer. For efficiency, Jinx
highlights misspellings lazily, recognizes window boundaries and text folding,
if any. For example, when unfolding or scrolling, only the newly visible part of
the text is checked if it has not been checked before. Each misspelling can be
corrected from a list of dictionary words presented as a completion menu.

#+begin_src emacs-lisp
  (use-package jinx
    :delight
    :demand t
    :general
    (general-def jinx-mode-map
      "C-&" 'jinx-correct)
    :config
    (global-jinx-mode 1))
#+end_src

* Wucuo
=wucuo= is a fast wrapper around =flyspell= designed to keep your workflow
snappy. =flyspell= can make Emacs notoriously sluggish when activated in the
conventional way. =wucuo= gets around =flyspell='s shortcomings by only calling
=flyspell= in certain circumstances, such as when a buffer is saved to disk, or
after a specified time interval.

#+begin_src emacs-lisp
  (use-package wucuo
    ;; Jinx is faster and more practical.
    :disabled
    :hook
    (text-mode . wucuo-start)
    :delight
    :custom
    ;; How wucuo operates.
    ;; "fast": run `flyspell-region' in `after-save-hook' over visible region.
    ;; "normal": run `flyspell-buffer' in `after-save-hook'.
    (wucuo-flyspell-start-mode "fast")
    ;; How many seconds wucuo waits before running spell-check.
    (wucuo-update-interval 2)
    :init
    ;; Disable flyspell-mode before using wucuo
    (when (bound-and-true-p flyspell-mode)
      (flyspell-mode -1))
    (when (bound-and-true-p flyspell-prog-mode)
      (flyspell-prog-mode -1))
    ;; Tell wucuo to ignore certain majore modes.
    (setq wucuo-spell-check-buffer-predicate
          (lambda ()
            (not (memq major-mode
                       '(dired-mode
                         log-edit-mode
                         compilation-mode
                         help-mode
                         profiler-report-mode
                         speedbar-mode
                         gud-mode
                         calc-mode
                         Info-mode))))))
#+end_src
