#+TITLE:   TRAMP: Interact with Remote Resources
#+AUTHOR:  Tom Trabue
#+EMAIL:   tom.trabue@gmail.com
#+DATE:    2021-07-13
#+TAGS:    tramp remote resource resources file edit
#+STARTUP: fold

This file contains plugins for TRAMP and their configurations. You will find the
main TRAMP configuration code in =my-init.org= since we need to specify TRAMP's
configuration early in Emacs' loading process.

* docker-tramp
This is a built-in Emacs package that offers the TRAMP method =docker= for
interacting with running Docker containers.

Use =C-x C-f /docker:user@container:/path/to/file=, where =user= is the user you
want to use inside of the container (optional), and =container= is the name of
the container you want to access.

For example, if you want to access a Docker container as the root user:
=/sudo:root@localhost|docker:user@container:/path/to/file=

#+begin_src emacs-lisp
  (when (< emacs-major-version 29)
    ;; For some reason, the :if keyword does not appear to work in use-package.
    (use-package docker-tramp
      ;; This feature is built into Emacs 29+ as `tramp-container'.
      :if (< emacs-major-version 29)))
#+end_src

* vagrant-tramp
=vagrant-tramp= adds an Emacs TRAMP method for Vagrant boxes. As far as Vagrant
is concerned, the TRAMP =vagrant= method behaves like the built-in =vagrant ssh=
command. The =vagrant-tramp= method simply provides auto-completion and a
wrapper around =vagrant ssh= for connecting to boxes.

#+begin_src emacs-lisp
  (use-package vagrant-tramp
    ;; I have no use for this plugin at this time.
    ;; Enable if desired.
    :disabled)
#+end_src
