#+TITLE:   Vertico: Minimal Completion UI
#+AUTHOR:  Tom Trabue
#+EMAIL:   tom.trabue@gmail.com
#+DATE:    2021-07-21
#+TAGS:    vertico minibuffer completion framework candidate
#+STARTUP: fold

=vertico= provides a Helm-like completion UI for several completion frameworks,
including the built-in Emacs completion system and the =consult=
framework. Please keep in mind that =vertico= is only the UI. It is not a
completion framework unto itself. The idea is that Vertico is *totally*
compatible with Emacs' =completing-read= API, meaning that any functions that
use =completing-read= for completion can benefit from Vertico's sleek narrowing
search front-end. Thus, Vertico really is a /replacement/ for Emacs' completion
UI, as well as an enhancement.

* Vertico vs. other narrowing completion UIs
Vertico is an alternative to completion frameworks such as Selectrum, Ivy,
Helm, IDO, =icomplete-vertical=, etc. The main difference is that Vertico aims
to be as minimal as possible, only providing a pretty UI and deferring the
completion system to other plugins, such as the built-in Emacs completion
system or =orderless=. Vertico is probably most similar to IComplete since
both are fully compatible with =completing-read=, although Vertico has far
more features and looks nicer than IComplete. Selectrum is nearly as pure as
Vertico, but does contain some custom filtering logic that keeps it from full
=completing-read= compatibility. Vertico is also probably the most flexible
completion UI in terms of customization.

* Functions
#+begin_src emacs-lisp
  (defun my/crm-indicator (args)
    "Add a prompt to `completing-read-multiple'.

  Display [CRM<separator>], e.g., [CRM,] if the separator is a comma."
    (cons (format "[CRM%s] %s"
                  (replace-regexp-in-string
                   "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                   crm-separator)
                  (car args))
          (cdr args)))
#+end_src

* =use-package= specification
#+begin_src emacs-lisp
  (use-package vertico
    :after evil-collection
    :demand t
    :general
    (general-def vertico-map
      "?" 'minibuffer-completion-help
      "C-j" 'vertico-next
      "C-k" 'vertico-previous
      "C-d" 'vertico-scroll-up
      "C-u" 'vertico-scroll-down
      "C-o" 'vertico-first
      "C-i" 'vertico-last
      "C-M-j" 'vertico-exit-input)
    (general-def 'normal vertico-map
      ;; Pressing ? brings up help for available completions
      "?" 'minibuffer-completion-help)
    (general-def '(normal insert) vertico-map
      ;; Navigate vertico with C-j and C-k
      "C-j" 'vertico-next
      "C-k" 'vertico-previous
      ;; I know it looks backwards, but this makes more sense in practice.
      ;; Vertico considers further down the list as "scrolling up", and vice
      ;; versa.
      "C-d" 'vertico-scroll-up
      "C-u" 'vertico-scroll-down
      ;; Go to top or bottom of minibuffer
      "C-o" 'vertico-first
      "C-i" 'vertico-last
      ;; Complete current selection
      "C-l" 'vertico-insert
      "TAB" 'vertico-insert
      "M-TAB" 'minibuffer-complete
      "M-RET" 'minibuffer-force-complete-and-exit
      ;; Select currently typed text and exit Vertico
      "C-M-j" 'vertico-exit-input)
    :custom
    ;; Whether to grow and shrink vertico buffer dynamically
    ;; Can be t (which means grow and shrink), nil, or 'grow-only
    (vertico-resize nil)
    ;; Max number of candidates to show
    (vertico-count 20)
    ;; Enable cycling for vertico-next and vertico-previous
    (vertico-cycle t)
    ;; The number of lines at the top and bottom of the candidate view when scrolling
    (vertico-scroll-margin 2)
    ;; Configure the Vertico display per command.
    ;; Takes precedence over `vertico-multiform-categories'.
    (vertico-multiform-commands
     '((affe-grep buffer)
       (consult-grep buffer)
       (consult-imenu buffer indexed)
       (consult-outline buffer indexed)
       (consult-line buffer)
       (consult-line-multi buffer)))
    ;; Configure the display per completion category.
    (vertico-multiform-categories
     '((file grid)
       (imenu buffer)))
    :init
    (when (< emacs-major-version 31)
      ;; Older versions of Emacs do not indicate to the user that multiple strings can be completed
      ;; via `completing-read-multiple', so we fix that behavior here.
      (advice-add #'completing-read-multiple :filter-args #'my/crm-indicator))
    :config
    ;; Enable Vertico globally.
    (vertico-mode 1)
    ;; `vertico-multiform-mode' allows you to style and configure Vertico per completion category
    ;; rather than globally.
    (vertico-multiform-mode 1))
#+end_src

* Extensions
** vertico-directory
Configure directory extension.

#+begin_src emacs-lisp
  (use-package vertico-directory
    :after vertico
    ;; Vertico extensions come with the repo.
    :ensure nil
    :straight nil
    :hook
    ;; Tidy shadowed file names
    (rfn-eshadow-update-overlay . vertico-directory-tidy))
#+end_src

** vertico-mouse
Mouse integration for Vertico.

#+begin_src emacs-lisp
  (use-package vertico-mouse
    :after vertico
    ;; Vertico extensions come with the repo.
    :ensure nil
    :straight nil
    :hook
    (vertico-mode . vertico-mouse-mode))
#+end_src

* Plugins
** vertico-posframe
=vertico-posframe= lets Vertico use =posframe= to display its candidate menu, which
is a modern looking child frame in the middle of the active Emacs frame.

#+begin_src emacs-lisp
  (use-package vertico-posframe
    :after (vertico consult)
    ;; Only usable in GUI Emacs.
    :if (display-graphic-p)
    :hook
    (vertico-mode . vertico-posframe-mode)
    :init
    (defun my/vertico-posframe-top-center (multiform-cmd)
      "Position the posframe at the top center of the parent frame."
      (list multiform-cmd
            'posframe
            '(vertico-posframe-poshandler . posframe-poshandler-frame-top-center)
            '(vertico-posframe-border-width . 10)
            ;; NOTE: This is useful when emacs is used in both in X and terminal since posframe does
            ;; not work well in terminal, so `vertico-buffer-mode' will be used as the fallback
            ;; display style.
            '(vertico-posframe-fallback-mode . vertico-buffer-mode)))
    (setq vertico-multiform-categories (append vertico-multiform-categories
                                               (list (my/vertico-posframe-top-center 'consult-line)
                                                     '(t posframe)))))
#+end_src
