#+TITLE:  Whitespace Management
#+AUTHOR: Tom Trabue
#+EMAIL:  tom.trabue@gmail.com
#+DATE:   2020-06-20
#+TAGS:   whitespace strip trailing
#+STARTUP: fold

Here we place plugins for managing whitespace across files as you edit them. The
ability to edit an existing file while both respecting existing whitespace
content and not introducing more trailing whitespace is a mark of a seasoned and
professional software developer. This practice accomplishes two important tasks:
first, it ensures that any commits you make to a codebase have as few edited
lines as necessary, and second, it keeps your code contributions clean.

* whitespace [built-in]
=whitespace.el= is a built-in package for handling whitespace-related editing
concerns, such as trimming trailing whitespace, or highlighting whitespace
characters under certain circumstances using =whitespace-mode=.

#+begin_src emacs-lisp
  (use-package whitespace
    :demand t
    :delight
    (whitespace-mode nil whitespace)
    :hook
    (;; Deactivate `whitespace-mode' in certain minor modes.
     (Buffer-menu-mode minibuffer-mode org-mode) . (lambda () (whitespace-mode -1)))
    :custom
    ;; The max column width for a line after which whitespace-mode highlights characters that exceed
    ;; this width.
    (whitespace-line-column my/line-width)
    ;; Determine the kinds of whitespace to be visualized.  The value of this variable is a list of
    ;; symbols, each of which has rich meaning, so I will not repeat them here.  See the variable's
    ;; documentation for details.
    (whitespace-style '(face trailing lines-tail tabs tab-mark empty))
    :config
    ;; Globally enable `whitespace-mode' by default.
    (global-whitespace-mode 1))
#+end_src

* whitespace-cleanup-mode
Cleans trailing whitespace when saving a buffer, but only for edited lines of
code.

#+begin_src emacs-lisp
  (use-package whitespace-cleanup-mode
    :demand t
    :delight
    :config
    (global-whitespace-cleanup-mode 1))
#+end_src

* clean-aindent-mode
This minor mode makes sure to trim trailing whitespace left over once you press
Return on your keyboard and =electric-indent-mode= places your cursor at an
indented column on the new line. Normally, if you use your navigation keys to
move the cursor off of that indented location, Emacs preserves any trailing
spaces.  However, =clean-aindent-mode= will remove those spaces once your cursor
moves away.

#+begin_src emacs-lisp
  (use-package clean-aindent-mode
    ;; Old, unmaintained, unnecessary, a little buggy
    :disabled
    :demand t
    :custom
    (clean-aindent-is-simple-indent t)
    :config
    ;; Turn off electric-indent-mode, since auto-indent is
    ;; sufficient.
    (electric-indent-mode -1)
    (clean-aindent-mode 1))
#+end_src

* dtrt-indent
An Emacs minor mode that guesses the indentation offset originally used for
creating source code files and transparently adjusts the corresponding settings
in Emacs, making it more convenient to edit foreign files.

#+begin_src emacs-lisp
  (use-package dtrt-indent
    :demand t
    :delight
    :custom
    (dtrt-indent-verbosity 0)
    :config
    (dtrt-indent-global-mode 1))
#+end_src
