#+title:  Whitespace Management
#+author: Tom Trabue
#+email:  tom.trabue@gmail.com
#+date:   2020:06:20
#+tags:   whitespace strip trailing
#+STARTUP: fold

Here we place plugins for managing whitespace across files as you edit them. The
ability to edit an existing file while both respecting existing whitespace
content and not introducing more trailing whitespace is a mark of a seasoned and
professional software developer. This practice accomplishes two important tasks:
first, it ensures that any commits you make to a code base have as few edited
lines as is necessary, and second, it keeps your code contributions clean.

* whitespace-cleanup-mode
  Cleans trailing whitespace on buffer save, but only for lines of code that
  have been edited.

#+begin_src emacs-lisp
  (use-package whitespace-cleanup-mode
    :demand t
    :config
    (global-whitespace-cleanup-mode 1))
#+end_src

* clean-aindent-mode
  This minor mode makes sure to trim trailing whitespace left over once you hit
  Return on your keyboard and =electric-indent-mode= places your cursor at an
  indented column on the new line. Normally, if you use your navigation keys to
  move the cursor off of that indented location, then the whitespace is left
  hanging there. However, with =clean-aindent-mode= those spaces will be removed
  once your cursor moves away.

#+begin_src emacs-lisp
  (use-package clean-aindent-mode
    ;; Old, unmaintained, unnecessary, a little buggy
    :disabled
    :demand t
    :custom
    (clean-aindent-is-simple-indent t)
    :config
    ;; Turn off electric-indent-mode, since auto-indent is
    ;; sufficient.
    (electric-indent-mode -1)
    (clean-aindent-mode 1))
#+end_src

* dtrt-indent
  An Emacs minor mode that guesses the indentation offset originally used for
  creating source code files and transparently adjusts the corresponding
  settings in Emacs, making it more convenient to edit foreign files.

#+begin_src emacs-lisp
  (use-package dtrt-indent
    :demand t
    :custom
    (dtrt-indent-verbosity 0)
    :config
    (dtrt-indent-mode 1))
#+end_src
