#+TITLE:  Whitespace Management
#+AUTHOR: Tom Trabue
#+EMAIL:  tom.trabue@gmail.com
#+DATE:   2020-06-20
#+TAGS:   whitespace strip trailing
#+STARTUP: fold

Here we place plugins for managing whitespace across files as you edit them. The
ability to edit an existing file while both respecting existing whitespace
content and not introducing more trailing whitespace is a mark of a seasoned and
professional software developer. This practice accomplishes two important tasks:
first, it ensures that any commits you make to a codebase have as few edited
lines as necessary, and second, it keeps your code contributions clean.

* whitespace-cleanup-mode
Cleans trailing whitespace when saving a buffer, but only for edited lines of
code.

#+begin_src emacs-lisp
  (use-package whitespace-cleanup-mode
    :demand t
    :config
    (global-whitespace-cleanup-mode 1))
#+end_src

* clean-aindent-mode
This minor mode makes sure to trim trailing whitespace left over once you press
Return on your keyboard and =electric-indent-mode= places your cursor at an
indented column on the new line. Normally, if you use your navigation keys to
move the cursor off of that indented location, Emacs preserves any trailing
spaces.  However, =clean-aindent-mode= will remove those spaces once your cursor
moves away.

#+begin_src emacs-lisp
  (use-package clean-aindent-mode
    ;; Old, unmaintained, unnecessary, a little buggy
    :disabled
    :demand t
    :custom
    (clean-aindent-is-simple-indent t)
    :config
    ;; Turn off electric-indent-mode, since auto-indent is
    ;; sufficient.
    (electric-indent-mode -1)
    (clean-aindent-mode 1))
#+end_src

* dtrt-indent
An Emacs minor mode that guesses the indentation offset originally used for
creating source code files and transparently adjusts the corresponding settings
in Emacs, making it more convenient to edit foreign files.

#+begin_src emacs-lisp
  (use-package dtrt-indent
    :hook
    ((prog-mode text-mode) . dtrt-indent-mode)
    :custom
    (dtrt-indent-verbosity 0))
#+end_src
