# The "PC Speaker" is a simple sound output device capable of prodiucing beeps 
# to alert the user to various events, but not sophisticated sound output. It 
# also tends to be super annoying, so most users disable this beep by 
# blacklisting the following kernel modules.

blacklist pcspkr
blacklist snd_pcsp
