# This page lists helpful documentation for NVIDIA kernel module parameter:
# https://wiki.gentoo.org/wiki/NVIDIA/nvidia-drivers

# Do not load the 'nvidiafb' or 'nouveau' modules on boot.
# This may help prevent errors when resuming from a suspended session.
blacklist nvidiafb
blacklist nouveau

options nvidia NVreg_RegistryDwords="OverrideMaxPerf=0x1"
# Use PAT technology on newer CPUs. This supersedes the use of MTRR.
options nvidia NVreg_UsePageAttributeTable=1
# Enable or disable use of GSP firmware. Turing and later GPUs include a GPU 
# System Processor (GSP) which can be used to offload GPU initialization and 
# management tasks. When using GSP firmware, the driver will not yet correctly 
# support display-related features or power management related features. These 
# features will be added to GSP firmware in future driver releases.
options nvidia NVreg_EnableGpuFirmware=1
# Do not wipe allocated memory before zeroing out its content. This provides
# a slight performance boost at the cost of increased security risks.
options nvidia NVreg_InitializeSystemMemoryAllocations=0
# Power management
# Save all video memory to a temporary file before suspending.
options nvidia NVreg_PreserveVideoMemoryAllocations=1 
options nvidia NVreg_TemporaryFilePath=/var/tmp
# Needed for PRIME hybrid graphics rendering.
options nvidia "NVreg_DynamicPowerManagement=0x02"
