#+title:    Helpful Arch Linux Notes
#+author:   Tom Trabue
#+email:    tom.trabue@gmail.com
#+date:     2021:01:22
#+tags:

* Graphical Issues
  First thing's first, make sure you are using the correct driver for your
  purposes. If you are running multiple monitors, you almost always want to use
  the proprietary NVIDIA driver.

** Screen Discoloration under NVIDIA proprietary driver
   If you experience screen discoloration when a screen updates, such as when
   scrolling a browser, make sure you have the following options set in your
   =/etc/X11/xorg.conf.d/20-nvidia.conf= file. Note that your board name will
   most likely be different than what is listed below:

#+begin_src sh
Section "Device"
  Identifier     "Device0"
  Driver         "nvidia"
  VendorName     "NVIDIA Corporation"
  BoardName      "GeForce GTX 1650 with Max-Q Design"
  Option         "TripleBuffer" "True"
  Option         "AllowIndirectGLXProtocol" "off"
EndSection
#+end_src

** Monitors not detected by xrandr or nvidia-settings
   If your monitors are not detected by running =xrandr -q= even though they are
   plugged in and powered on, then you can usually solve this problem by
   doing the following:

   - Make sure all monitors are plugged in and powered on,
   - If using a laptop with an NVIDIA graphics card, install and enable the
     =optimus-manager= service,
   - Restart your computer and check =xrandr= and =nvidia-settings=,
   - If monitors are still not detected, put computer to sleep, let sit for
     about 10 minutes, and then wake back up and check =xrandr= and
     =nvidia-settings=.

   Unfortunately, there are no surefire ways to force Linux to detect
   monitors. All I can do is tell you what has worked for me in the past. This
   issue is typically a sporadic and annoying one that thankfully tends to
   resolve itself.
