#+TITLE:   Configure NVIDIA on Arch Linux
#+AUTHOR:  Thomas Trabue
#+EMAIL:   tom.trabue@gmail.com
#+DATE:    2025-04-11
#+TAGS:    nvidia arch linux arch_linux graphics gpu
#+STARTUP: fold

Almost all of the important documentation for installing and configuring NVIDIA
drivers and supporting software comes from the [[https://wiki.archlinux.org/title/NVIDIA][Arch Wiki page]], and I suggest you
read that article in its entirety. This page seeks to distill information from a
plethora of Arch Wiki pages, help pages, FAQs, and other random places on the
internet so that users can quickly get their NVIDIA configurations up and
running on a new Arch installation.

* Install the correct driver
Visit the official Arch Wiki page for NVIDIA for guidance on which driver to use
for your graphics card.

* Configure NVIDIA kernel module parameters in the bootloader configuration
** GRUB
Open =/etc/default/grub= and add the following to =GRUB_CMDLINE_LINUX_DEFAULT=:

#+begin_src conf :tangle no
  # The elipsis represents other parameters that may already exist in this string.
  GRUB_CMDLINE_LINUX_DEFAULT="... nvidia-drm.modeset=1 nvidia-drm.fbdev=1"
#+end_src

Now, regenerate your GRUB configuration:

#+begin_src sh :tangle no
  sudo grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB

  sudo grub-mkconfig -o /boot/grub/grub.cfg
#+end_src

* Add early init configuration to initramfs manager
** mkinitcpio
If you use =mkinitcpio= to create an initial ramdisk image for early module
loading, add the following to the =MODULES()= array in =/etc/mkinitcpio.conf=

#+begin_src conf :tangle no
  MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
#+end_src

You must also *remove* =kms= from the =HOOKS()= array in that same file if it is
present.

Next, regenerate the initramfs:

#+begin_src sh :tangle no
  sudo mkinitcpio -P
#+end_src

* pacman hook

Create a Pacman hook file =/etc/pacman.d/hooks/nvidia.hook= with the following contents:

#+begin_src conf :tangle no
  [Trigger]
  Operation=Install
  Operation=Upgrade
  Operation=Remove
  Type=Package
  # You can remove package(s) that don't apply to your config, e.g. if you only use nvidia-open you can remove nvidia-lts as a Target
  Target=nvidia
  Target=nvidia-lts
  Target=nvidia-open
  Target=nvidia-open-lts
  # If running a different kernel, modify below to match
  Target=linux
  Target=linux-lts

  [Action]
  Description=Updating NVIDIA module in initcpio
  Depends=mkinitcpio
  When=PostTransaction
  NeedsTargets
  Exec=/bin/sh -c 'while read -r trg; do case $trg in linux*) exit 0; esac; done; /usr/bin/mkinitcpio -P'
#+end_src

* NVIDIA Optimus
If you own a laptop that includes a discrete NVIDIA GPU, then you have an NVIDIA
Optimus device. Optimus is NVIDIA technology that allows a laptop to use both
integrated graphics via the computer's CPU alongside graphics from the GPU, and
to switch between those drivers without requiring a reboot. However, you will
need to configure Arch for Optimus, which includes writing both an Xorg
configuration file and a setup script for your Display Manager (DM) of
choice. Visit the official [[https://wiki.archlinux.org/title/NVIDIA_Optimus][Arch Wiki page]] for details.

* Create modprobe file for NVIDIA kernel modules parameters

Create a file =/etc/modprobe.d/nvidia.conf= with the following contents:

#+begin_src conf :tangle no
  ### Power management
  # Save all video memory to a temporary file under `/var/tmp' when Systemd
  # suspends the system.
  options nvidia NVreg_UsePageAttributeTable=1 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp
  # Do not load the 'nvidiafb' module on boot.
  # This may help prevent errors when resuming from a suspended session.
  blacklist nvidiafb
  # We wish to use the proprietary NVIDIA driver, not the open source Nouveau
  # driver.
  blacklist nouveau
#+end_src

Please check the [[https://wiki.gentoo.org/wiki/NVIDIA/nvidia-drivers][Gentoo Wiki]] page for detailed documentation about NVIDIA's
kernel module parameters.

* Enable NVIDIA services

Enable the following NVIDIA Systemd services:

#+begin_src sh :tangle no
  # Use NVIDIA to suspend system
  sudo systemctl enable nvidia-suspend
  # Use NVIDIA to hibernate system
  sudo systemctl enable nvidia-hibernate
  # Use NVIDIA to resume from suspend/hibernate
  # NOTE: This service sometimes causes problems resuming! You may want to
  #       disable this service should that occur.
  sudo systemctl enable nvidia-resume
  # Manages saved video memory during suspend/hibernate
  sudo systemctl enable nvidia-persistenced
#+end_src
