#!/bin/sh

# NOTE: This line was auto-generated by the `export_path` function. You
#       should not edit it, as it will eventually be regenerated and your
#       changes will be lost. Instead, add your PATH entries to ~/.path.
export PATH="${HOME}/workspace/flutter/bin:${HOME}/perl5/bin:${HOME}/go/bin:${HOME}/.asdf/bin:${HOME}/.roswell/bin:${HOME}/.rvm/gems/default/bin:${HOME}/.rvm/rubies/default/bin:${HOME}/.rvm/bin:${HOME}/.pyenv/versions/3.9.7/bin:${HOME}/.pyenv/shims:${HOME}/.pyenv/bin:${HOME}/.sdkman/candidates/maven/current/bin:${HOME}/.sdkman/candidates/kotlin/current/bin:${HOME}/.sdkman/candidates/java/current/bin:${HOME}/.sdkman/candidates/gradle/current/bin:${HOME}/.jenv/bin:${HOME}/.cargo/bin:${HOME}/.npm-global/bin:${HOME}/.luarocks/bin:${HOME}/.cabal/bin:${HOME}/.ghcup/bin:${HOME}/.fzf/bin:${HOME}/.dotfiles/bin:${HOME}/.local/bin:${HOME}/bin:/usr/local/Cellar/libtool/2.4.6_4/libexec/gnubin:/usr/local/Cellar/grep/3.7/libexec/gnubin:/usr/local/Cellar/gnu-which/2.21/libexec/gnubin:/usr/local/Cellar/gnu-tar/1.34/libexec/gnubin:/usr/local/Cellar/gnu-sed/4.8/libexec/gnubin:/usr/local/Cellar/gnu-indent/2.2.12_1/libexec/gnubin:/usr/local/Cellar/gawk/5.1.1/libexec/gnubin:/usr/local/Cellar/findutils/4.8.0_1/libexec/gnubin:/usr/local/Cellar/ed/1.17/libexec/gnubin:/usr/local/Cellar/coreutils/9.0/libexec/gnubin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin:/sbin:/bin"

# vim:foldenable:foldmethod=marker:foldlevel=0
