#!/bin/sh

# IMPORTANT: This line is auto-generated by the `export_path()` function.
export PATH="/usr/local/opt/llvm/bin:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/gnu-which/libexec/gnubin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-indent/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/gawk/libexec/gnubin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/openssh/bin:/usr/local/opt/gnu-getopt/bin:/usr/local/opt/binutils/bin:/Users/thomastrabue/perl5/bin:/Users/thomastrabue/go/bin:/Users/thomastrabue/.asdf/bin:/Users/thomastrabue/.rvm/bin:/Users/thomastrabue/.pyenv/bin:/Users/thomastrabue/.jenv/bin:/Users/thomastrabue/.cargo/bin:/Users/thomastrabue/.npm-global/bin:/Users/thomastrabue/.luarocks/bin:/Users/thomastrabue/.cabal/bin:/Users/thomastrabue/.ghcup/bin:/Users/thomastrabue/.fzf/bin:/Users/thomastrabue/.dotfiles/bash/bin:/Users/thomastrabue/.local/bin:/Users/thomastrabue/bin:/usr/local/bin:/usr/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin:/sbin:/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
