#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# Set desktops on various connected displays
bspc monitor -d I II III IV
if xrandr -q | grep -E -q "DP-0\s*connected"; then
  bspc monitor DP-0 -d I V VI VII VII
fi
if xrandr -q | grep -E -q "DP-1\s*connected"; then
  bspc monitor DP-1 -d VIII IX X
fi

# Load multi-monitor configuration
defaultArandrProfileFile="${HOME}/.screenlayout/default.sh"
if [ -f "${defaultArandrProfileFile}" ]; then
  sh "${defaultArandrProfileFile}"
  bspc monitor eDP-1-1 -d I II III IV
  bspc monitor DP-0 -d I V VI VII VII
  bspc monitor DP-1 -d VIII IX X
fi
unset defaultArandrProfileFile

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

### Auto-start applications ###

# Start the compositing manager in the background
picom --config "${HOME}/.config/picom/picom.conf" &

# Wallpaper
# Use feh commands in ~/.fehbg to set wallpaper
"${HOME}/.fehbg" &

# Notification
dunst &

# System Panel
polybar &

# Modeline for this file (LEAVE IT COMMENTED!)
# vim:foldenable:foldmethod=marker:foldlevel=0
