#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# Load multi-monitor configuration
defaultArandrProfileFile="${HOME}/.screenlayout/default.sh"
if [ -f "${defaultArandrProfileFile}" ]; then
  sh "${defaultArandrProfileFile}"
  bspc monitor eDP-1-1 -d I II III IV
  bspc monitor DP-0 -d I V VI VII VII
  bspc monitor DP-1 -d VIII IX X
fi
unset defaultArandrProfileFile

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

### Auto-start applications ###

# Start the compositing manager in the background
picom --config "${HOME}/.config/picom/picom.conf" &

# Wallpaper
nitrogen --restore &

# Notification
dunst &

# System Panel
polybar &
